# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/sony/shinano-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter amami castor castor_windy honami sirius togari z3 z3c z3dual,$(TARGET_DEVICE)),)

endif
