# Copyright (C) 2011-2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/scorpion/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/sony/scorpion/proprietary/etc/firmware/modem.b00:system/etc/firmware/modem.b00 \
    vendor/sony/scorpion/proprietary/etc/firmware/modem.b01:system/etc/firmware/modem.b01 \
    vendor/sony/scorpion/proprietary/etc/firmware/modem.b02:system/etc/firmware/modem.b02 \
    vendor/sony/scorpion/proprietary/etc/firmware/modem.b03:system/etc/firmware/modem.b03 \
    vendor/sony/scorpion/proprietary/etc/firmware/modem.b06:system/etc/firmware/modem.b06 \
    vendor/sony/scorpion/proprietary/etc/firmware/modem.b08:system/etc/firmware/modem.b08 \
    vendor/sony/scorpion/proprietary/etc/firmware/modem.b09:system/etc/firmware/modem.b09 \
    vendor/sony/scorpion/proprietary/etc/firmware/modem.b11:system/etc/firmware/modem.b11 \
    vendor/sony/scorpion/proprietary/etc/firmware/modem.b12:system/etc/firmware/modem.b12 \
    vendor/sony/scorpion/proprietary/etc/firmware/modem.b13:system/etc/firmware/modem.b13 \
    vendor/sony/scorpion/proprietary/etc/firmware/modem.b14:system/etc/firmware/modem.b14 \
    vendor/sony/scorpion/proprietary/etc/firmware/modem.b15:system/etc/firmware/modem.b15 \
    vendor/sony/scorpion/proprietary/etc/firmware/modem.b16:system/etc/firmware/modem.b16 \
    vendor/sony/scorpion/proprietary/etc/firmware/modem.b17:system/etc/firmware/modem.b17 \
    vendor/sony/scorpion/proprietary/etc/firmware/modem.b18:system/etc/firmware/modem.b18 \
    vendor/sony/scorpion/proprietary/etc/firmware/modem.b19:system/etc/firmware/modem.b19 \
    vendor/sony/scorpion/proprietary/etc/firmware/modem.b22:system/etc/firmware/modem.b22 \
    vendor/sony/scorpion/proprietary/etc/firmware/modem.b23:system/etc/firmware/modem.b23 \
    vendor/sony/scorpion/proprietary/etc/firmware/modem.b24:system/etc/firmware/modem.b24 \
    vendor/sony/scorpion/proprietary/etc/firmware/modem.b25:system/etc/firmware/modem.b25 \
    vendor/sony/scorpion/proprietary/etc/firmware/modem.mdt:system/etc/firmware/modem.mdt \
    vendor/sony/scorpion/proprietary/etc/tfa98xx/FMSpeaker_btm.eq:system/etc/tfa98xx/FMSpeaker_btm.eq \
    vendor/sony/scorpion/proprietary/etc/tfa98xx/FMSpeaker_btm.preset:system/etc/tfa98xx/FMSpeaker_btm.preset \
    vendor/sony/scorpion/proprietary/etc/tfa98xx/FMSpeaker_top.eq:system/etc/tfa98xx/FMSpeaker_top.eq \
    vendor/sony/scorpion/proprietary/etc/tfa98xx/FMSpeaker_top.preset:system/etc/tfa98xx/FMSpeaker_top.preset \
    vendor/sony/scorpion/proprietary/etc/tfa98xx/HiFiSpeakerRing_btm.eq:system/etc/tfa98xx/HiFiSpeakerRing_btm.eq \
    vendor/sony/scorpion/proprietary/etc/tfa98xx/HiFiSpeakerRing_btm.preset:system/etc/tfa98xx/HiFiSpeakerRing_btm.preset \
    vendor/sony/scorpion/proprietary/etc/tfa98xx/HiFiSpeakerRing_top.eq:system/etc/tfa98xx/HiFiSpeakerRing_top.eq \
    vendor/sony/scorpion/proprietary/etc/tfa98xx/HiFiSpeakerRing_top.preset:system/etc/tfa98xx/HiFiSpeakerRing_top.preset \
    vendor/sony/scorpion/proprietary/etc/tfa98xx/HiFiSpeakerSforce_btm.eq:system/etc/tfa98xx/HiFiSpeakerSforce_btm.eq \
    vendor/sony/scorpion/proprietary/etc/tfa98xx/HiFiSpeakerSforce_btm.preset:system/etc/tfa98xx/HiFiSpeakerSforce_btm.preset \
    vendor/sony/scorpion/proprietary/etc/tfa98xx/HiFiSpeakerSforce_top.eq:system/etc/tfa98xx/HiFiSpeakerSforce_top.eq \
    vendor/sony/scorpion/proprietary/etc/tfa98xx/HiFiSpeakerSforce_top.preset:system/etc/tfa98xx/HiFiSpeakerSforce_top.preset \
    vendor/sony/scorpion/proprietary/etc/tfa98xx/HiFiSpeaker_btm.eq:system/etc/tfa98xx/HiFiSpeaker_btm.eq \
    vendor/sony/scorpion/proprietary/etc/tfa98xx/HiFiSpeaker_btm.preset:system/etc/tfa98xx/HiFiSpeaker_btm.preset \
    vendor/sony/scorpion/proprietary/etc/tfa98xx/HiFiSpeaker_top.eq:system/etc/tfa98xx/HiFiSpeaker_top.eq \
    vendor/sony/scorpion/proprietary/etc/tfa98xx/HiFiSpeaker_top.preset:system/etc/tfa98xx/HiFiSpeaker_top.preset \
    vendor/sony/scorpion/proprietary/etc/tfa98xx/TFA9890.patch:system/etc/tfa98xx/TFA9890.patch \
    vendor/sony/scorpion/proprietary/etc/tfa98xx/TFA9890_Receiver.config:system/etc/tfa98xx/TFA9890_Receiver.config \
    vendor/sony/scorpion/proprietary/etc/tfa98xx/TFA9890_btm.config:system/etc/tfa98xx/TFA9890_btm.config \
    vendor/sony/scorpion/proprietary/etc/tfa98xx/TFA9890_top.config:system/etc/tfa98xx/TFA9890_top.config \
    vendor/sony/scorpion/proprietary/etc/tfa98xx/VoiceCallEarpice_top.eq:system/etc/tfa98xx/VoiceCallEarpice_top.eq \
    vendor/sony/scorpion/proprietary/etc/tfa98xx/VoiceCallEarpice_top.preset:system/etc/tfa98xx/VoiceCallEarpice_top.preset \
    vendor/sony/scorpion/proprietary/etc/tfa98xx/VoiceCallSpeaker_btm.eq:system/etc/tfa98xx/VoiceCallSpeaker_btm.eq \
    vendor/sony/scorpion/proprietary/etc/tfa98xx/VoiceCallSpeaker_btm.preset:system/etc/tfa98xx/VoiceCallSpeaker_btm.preset \
    vendor/sony/scorpion/proprietary/etc/tfa98xx/VoiceCallSpeaker_top.eq:system/etc/tfa98xx/VoiceCallSpeaker_top.eq \
    vendor/sony/scorpion/proprietary/etc/tfa98xx/VoiceCallSpeaker_top.preset:system/etc/tfa98xx/VoiceCallSpeaker_top.preset \
    vendor/sony/scorpion/proprietary/etc/tfa98xx/btm.speaker:system/etc/tfa98xx/btm.speaker \
    vendor/sony/scorpion/proprietary/etc/tfa98xx/coldboot.patch:system/etc/tfa98xx/coldboot.patch \
    vendor/sony/scorpion/proprietary/etc/tfa98xx/top.speaker:system/etc/tfa98xx/top.speaker \
    vendor/sony/scorpion/proprietary/usr/idc/clearpad.idc:system/usr/idc/clearpad.idc
