# Copyright (C) 2014-2016 The CyanogenMod Project
# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/hayabusa/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/sony/hayabusa/proprietary/bin/clearpad_fwloader:system/bin/clearpad_fwloader \
    vendor/sony/hayabusa/proprietary/bin/updatemiscta:system/bin/updatemiscta \
    vendor/sony/hayabusa/proprietary/etc/firmware/dsps.b00:system/etc/firmware/dsps.b00 \
    vendor/sony/hayabusa/proprietary/etc/firmware/dsps.b01:system/etc/firmware/dsps.b01 \
    vendor/sony/hayabusa/proprietary/etc/firmware/dsps.b02:system/etc/firmware/dsps.b02 \
    vendor/sony/hayabusa/proprietary/etc/firmware/dsps.b03:system/etc/firmware/dsps.b03 \
    vendor/sony/hayabusa/proprietary/etc/firmware/dsps.b04:system/etc/firmware/dsps.b04 \
    vendor/sony/hayabusa/proprietary/etc/firmware/dsps.b05:system/etc/firmware/dsps.b05 \
    vendor/sony/hayabusa/proprietary/etc/firmware/dsps.mdt:system/etc/firmware/dsps.mdt \
    vendor/sony/hayabusa/proprietary/etc/firmware/dxhdcp2.b00:system/etc/firmware/dxhdcp2.b00 \
    vendor/sony/hayabusa/proprietary/etc/firmware/dxhdcp2.b01:system/etc/firmware/dxhdcp2.b01 \
    vendor/sony/hayabusa/proprietary/etc/firmware/dxhdcp2.b02:system/etc/firmware/dxhdcp2.b02 \
    vendor/sony/hayabusa/proprietary/etc/firmware/dxhdcp2.b03:system/etc/firmware/dxhdcp2.b03 \
    vendor/sony/hayabusa/proprietary/etc/firmware/dxhdcp2.mdt:system/etc/firmware/dxhdcp2.mdt \
    vendor/sony/hayabusa/proprietary/etc/firmware/touch_module_id_0x14.img:system/etc/firmware/touch_module_id_0x14.img \
    vendor/sony/hayabusa/proprietary/etc/firmware/touch_module_id_0x19.img:system/etc/firmware/touch_module_id_0x19.img \
    vendor/sony/hayabusa/proprietary/etc/firmware/touch_module_id_0x1a.img:system/etc/firmware/touch_module_id_0x1a.img \
    vendor/sony/hayabusa/proprietary/etc/firmware/touch_module_id_0xff.img:system/etc/firmware/touch_module_id_0xff.img \
    vendor/sony/hayabusa/proprietary/etc/firmware/tzlibasb.b00:system/etc/firmware/tzlibasb.b00 \
    vendor/sony/hayabusa/proprietary/etc/firmware/tzlibasb.b01:system/etc/firmware/tzlibasb.b01 \
    vendor/sony/hayabusa/proprietary/etc/firmware/tzlibasb.b02:system/etc/firmware/tzlibasb.b02 \
    vendor/sony/hayabusa/proprietary/etc/firmware/tzlibasb.b03:system/etc/firmware/tzlibasb.b03 \
    vendor/sony/hayabusa/proprietary/etc/firmware/tzlibasb.mdt:system/etc/firmware/tzlibasb.mdt \
    vendor/sony/hayabusa/proprietary/etc/firmware/tzs1sl.b00:system/etc/firmware/tzs1sl.b00 \
    vendor/sony/hayabusa/proprietary/etc/firmware/tzs1sl.b01:system/etc/firmware/tzs1sl.b01 \
    vendor/sony/hayabusa/proprietary/etc/firmware/tzs1sl.b02:system/etc/firmware/tzs1sl.b02 \
    vendor/sony/hayabusa/proprietary/etc/firmware/tzs1sl.b03:system/etc/firmware/tzs1sl.b03 \
    vendor/sony/hayabusa/proprietary/etc/firmware/tzs1sl.mdt:system/etc/firmware/tzs1sl.mdt \
    vendor/sony/hayabusa/proprietary/etc/firmware/tzsuntory.b00:system/etc/firmware/tzsuntory.b00 \
    vendor/sony/hayabusa/proprietary/etc/firmware/tzsuntory.b01:system/etc/firmware/tzsuntory.b01 \
    vendor/sony/hayabusa/proprietary/etc/firmware/tzsuntory.b02:system/etc/firmware/tzsuntory.b02 \
    vendor/sony/hayabusa/proprietary/etc/firmware/tzsuntory.b03:system/etc/firmware/tzsuntory.b03 \
    vendor/sony/hayabusa/proprietary/etc/firmware/tzsuntory.mdt:system/etc/firmware/tzsuntory.mdt \
    vendor/sony/hayabusa/proprietary/etc/flashled_calc_parameters.cfg:system/etc/flashled_calc_parameters.cfg \
    vendor/sony/hayabusa/proprietary/lib/hw/nfc.msm8960.so:system/lib/hw/nfc.msm8960.so \
    vendor/sony/hayabusa/proprietary/lib/libals.so:system/lib/libals.so \
    vendor/sony/hayabusa/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
    vendor/sony/hayabusa/proprietary/lib/libcald_client.so:system/lib/libcald_client.so \
    vendor/sony/hayabusa/proprietary/lib/libcald_hal.so:system/lib/libcald_hal.so \
    vendor/sony/hayabusa/proprietary/lib/libcald_imageutil.so:system/lib/libcald_imageutil.so \
    vendor/sony/hayabusa/proprietary/lib/libcald_pal.so:system/lib/libcald_pal.so \
    vendor/sony/hayabusa/proprietary/lib/libcald_server.so:system/lib/libcald_server.so \
    vendor/sony/hayabusa/proprietary/lib/libcald_util.so:system/lib/libcald_util.so \
    vendor/sony/hayabusa/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/sony/hayabusa/proprietary/vendor/camera/APT01BM0.dat:system/vendor/camera/APT01BM0.dat \
    vendor/sony/hayabusa/proprietary/vendor/camera/KMO13BS0.dat:system/vendor/camera/KMO13BS0.dat \
    vendor/sony/hayabusa/proprietary/vendor/camera/KMO13BS0_BU6456.dat:system/vendor/camera/KMO13BS0_BU6456.dat \
    vendor/sony/hayabusa/proprietary/vendor/camera/KMO13BS0_IMX091.dat:system/vendor/camera/KMO13BS0_IMX091.dat \
    vendor/sony/hayabusa/proprietary/vendor/camera/SOI13BS0.dat:system/vendor/camera/SOI13BS0.dat \
    vendor/sony/hayabusa/proprietary/vendor/camera/SOI13BS0_BU6456.dat:system/vendor/camera/SOI13BS0_BU6456.dat \
    vendor/sony/hayabusa/proprietary/vendor/camera/SOI13BS0_IMX091.dat:system/vendor/camera/SOI13BS0_IMX091.dat \
    vendor/sony/hayabusa/proprietary/vendor/camera/STW01BM0.dat:system/vendor/camera/STW01BM0.dat \
    vendor/sony/hayabusa/proprietary/vendor/camera/flash.dat:system/vendor/camera/flash.dat \
    vendor/sony/hayabusa/proprietary/vendor/camera/product.dat:system/vendor/camera/product.dat

PRODUCT_COPY_FILES += \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem.b00:system/etc/firmware/modem.b00 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem.b01:system/etc/firmware/modem.b01 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem.b02:system/etc/firmware/modem.b02 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem.b03:system/etc/firmware/modem.b03 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem.b04:system/etc/firmware/modem.b04 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem.b05:system/etc/firmware/modem.b05 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem.b06:system/etc/firmware/modem.b06 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem.b07:system/etc/firmware/modem.b07 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem.mdt:system/etc/firmware/modem.mdt \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_f1.b00:system/etc/firmware/modem_f1.b00 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_f1.b01:system/etc/firmware/modem_f1.b01 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_f1.b02:system/etc/firmware/modem_f1.b02 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_f1.b03:system/etc/firmware/modem_f1.b03 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_f1.b04:system/etc/firmware/modem_f1.b04 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_f1.b05:system/etc/firmware/modem_f1.b05 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_f1.b06:system/etc/firmware/modem_f1.b06 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_f1.b07:system/etc/firmware/modem_f1.b07 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_f1.b08:system/etc/firmware/modem_f1.b08 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_f1.b09:system/etc/firmware/modem_f1.b09 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_f1.b10:system/etc/firmware/modem_f1.b10 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_f1.b13:system/etc/firmware/modem_f1.b13 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_f1.b14:system/etc/firmware/modem_f1.b14 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_f1.b21:system/etc/firmware/modem_f1.b21 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_f1.b22:system/etc/firmware/modem_f1.b22 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_f1.b23:system/etc/firmware/modem_f1.b23 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_f1.b25:system/etc/firmware/modem_f1.b25 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_f1.b26:system/etc/firmware/modem_f1.b26 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_f1.b29:system/etc/firmware/modem_f1.b29 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_f1.mdt:system/etc/firmware/modem_f1.mdt \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_fw.b00:system/etc/firmware/modem_fw.b00 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_fw.b01:system/etc/firmware/modem_fw.b01 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_fw.b02:system/etc/firmware/modem_fw.b02 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_fw.b03:system/etc/firmware/modem_fw.b03 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_fw.b04:system/etc/firmware/modem_fw.b04 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_fw.b05:system/etc/firmware/modem_fw.b05 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_fw.b06:system/etc/firmware/modem_fw.b06 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_fw.b07:system/etc/firmware/modem_fw.b07 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_fw.b08:system/etc/firmware/modem_fw.b08 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_fw.b09:system/etc/firmware/modem_fw.b09 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_fw.b10:system/etc/firmware/modem_fw.b10 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_fw.b13:system/etc/firmware/modem_fw.b13 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_fw.b14:system/etc/firmware/modem_fw.b14 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_fw.b21:system/etc/firmware/modem_fw.b21 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_fw.b22:system/etc/firmware/modem_fw.b22 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_fw.b23:system/etc/firmware/modem_fw.b23 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_fw.b25:system/etc/firmware/modem_fw.b25 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_fw.b26:system/etc/firmware/modem_fw.b26 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_fw.b29:system/etc/firmware/modem_fw.b29 \
    vendor/sony/hayabusa/proprietary/etc/firmware/modem_fw.mdt:system/etc/firmware/modem_fw.mdt
