# Copyright (C) 2013-2016 The CyanogenMod Project
# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/odin/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/sony/odin/proprietary/bin/updatemiscta:system/bin/updatemiscta \
    vendor/sony/odin/proprietary/etc/firmware/apps.mbn:system/etc/firmware/apps.mbn \
    vendor/sony/odin/proprietary/etc/firmware/dsp1.mbn:system/etc/firmware/dsp1.mbn \
    vendor/sony/odin/proprietary/etc/firmware/dsp2.mbn:system/etc/firmware/dsp2.mbn \
    vendor/sony/odin/proprietary/etc/firmware/dsp3.mbn:system/etc/firmware/dsp3.mbn \
    vendor/sony/odin/proprietary/etc/firmware/dsps.b00:system/etc/firmware/dsps.b00 \
    vendor/sony/odin/proprietary/etc/firmware/dsps.b01:system/etc/firmware/dsps.b01 \
    vendor/sony/odin/proprietary/etc/firmware/dsps.b02:system/etc/firmware/dsps.b02 \
    vendor/sony/odin/proprietary/etc/firmware/dsps.b03:system/etc/firmware/dsps.b03 \
    vendor/sony/odin/proprietary/etc/firmware/dsps.b04:system/etc/firmware/dsps.b04 \
    vendor/sony/odin/proprietary/etc/firmware/dsps.b05:system/etc/firmware/dsps.b05 \
    vendor/sony/odin/proprietary/etc/firmware/dsps.mdt:system/etc/firmware/dsps.mdt \
    vendor/sony/odin/proprietary/etc/firmware/touch_module_id_0x34.img:system/etc/firmware/touch_module_id_0x34.img \
    vendor/sony/odin/proprietary/etc/firmware/touch_module_id_0x35.img:system/etc/firmware/touch_module_id_0x35.img \
    vendor/sony/odin/proprietary/etc/flashled_calc_parameters.cfg:system/etc/flashled_calc_parameters.cfg \
    vendor/sony/odin/proprietary/lib/hw/nfc.msm8960.so:system/lib/hw/nfc.msm8960.so \
    vendor/sony/odin/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
    vendor/sony/odin/proprietary/lib/libcald_server.so:system/lib/libcald_server.so \
    vendor/sony/odin/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/sony/odin/proprietary/vendor/camera/LGI02BN0_IMX132.dat:system/vendor/camera/LGI02BN0_IMX132.dat \
    vendor/sony/odin/proprietary/vendor/camera/SEM02BN0_IMX132.dat:system/vendor/camera/SEM02BN0_IMX132.dat \
    vendor/sony/odin/proprietary/vendor/camera/flash.dat:system/vendor/camera/flash.dat \
    vendor/sony/odin/proprietary/vendor/camera/product.dat:system/vendor/camera/product.dat

PRODUCT_COPY_FILES += \
    vendor/sony/odin/proprietary/bin/efsks:system/bin/efsks \
    vendor/sony/odin/proprietary/bin/qcks:system/bin/qcks
