# Copyright (C) 2011-2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/tianchi/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/sony/tianchi/proprietary/bin/fm_qsoc_patches:system/bin/fm_qsoc_patches \
    vendor/sony/tianchi/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/sony/tianchi/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
    vendor/sony/tianchi/proprietary/etc/firmware/adsp.b00:system/etc/firmware/adsp.b00 \
    vendor/sony/tianchi/proprietary/etc/firmware/adsp.b01:system/etc/firmware/adsp.b01 \
    vendor/sony/tianchi/proprietary/etc/firmware/adsp.b02:system/etc/firmware/adsp.b02 \
    vendor/sony/tianchi/proprietary/etc/firmware/adsp.b03:system/etc/firmware/adsp.b03 \
    vendor/sony/tianchi/proprietary/etc/firmware/adsp.b04:system/etc/firmware/adsp.b04 \
    vendor/sony/tianchi/proprietary/etc/firmware/adsp.b05:system/etc/firmware/adsp.b05 \
    vendor/sony/tianchi/proprietary/etc/firmware/adsp.b06:system/etc/firmware/adsp.b06 \
    vendor/sony/tianchi/proprietary/etc/firmware/adsp.b07:system/etc/firmware/adsp.b07 \
    vendor/sony/tianchi/proprietary/etc/firmware/adsp.b08:system/etc/firmware/adsp.b08 \
    vendor/sony/tianchi/proprietary/etc/firmware/adsp.b09:system/etc/firmware/adsp.b09 \
    vendor/sony/tianchi/proprietary/etc/firmware/adsp.b10:system/etc/firmware/adsp.b10 \
    vendor/sony/tianchi/proprietary/etc/firmware/adsp.b11:system/etc/firmware/adsp.b11 \
    vendor/sony/tianchi/proprietary/etc/firmware/adsp.b12:system/etc/firmware/adsp.b12 \
    vendor/sony/tianchi/proprietary/etc/firmware/adsp.mdt:system/etc/firmware/adsp.mdt \
    vendor/sony/tianchi/proprietary/etc/firmware/cmnlib.b00:system/etc/firmware/cmnlib.b00 \
    vendor/sony/tianchi/proprietary/etc/firmware/cmnlib.b01:system/etc/firmware/cmnlib.b01 \
    vendor/sony/tianchi/proprietary/etc/firmware/cmnlib.b02:system/etc/firmware/cmnlib.b02 \
    vendor/sony/tianchi/proprietary/etc/firmware/cmnlib.b03:system/etc/firmware/cmnlib.b03 \
    vendor/sony/tianchi/proprietary/etc/firmware/cmnlib.mdt:system/etc/firmware/cmnlib.mdt \
    vendor/sony/tianchi/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
    vendor/sony/tianchi/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
    vendor/sony/tianchi/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    vendor/sony/tianchi/proprietary/etc/firmware/cyttsp4_fw.bin:system/etc/firmware/cyttsp4_fw.bin \
    vendor/sony/tianchi/proprietary/etc/firmware/mba.b00:system/etc/firmware/mba.b00 \
    vendor/sony/tianchi/proprietary/etc/firmware/mba.mdt:system/etc/firmware/mba.mdt \
    vendor/sony/tianchi/proprietary/etc/firmware/modem.b00:system/etc/firmware/modem.b00 \
    vendor/sony/tianchi/proprietary/etc/firmware/modem.b01:system/etc/firmware/modem.b01 \
    vendor/sony/tianchi/proprietary/etc/firmware/modem.b02:system/etc/firmware/modem.b02 \
    vendor/sony/tianchi/proprietary/etc/firmware/modem.b03:system/etc/firmware/modem.b03 \
    vendor/sony/tianchi/proprietary/etc/firmware/modem.b04:system/etc/firmware/modem.b04 \
    vendor/sony/tianchi/proprietary/etc/firmware/modem.b05:system/etc/firmware/modem.b05 \
    vendor/sony/tianchi/proprietary/etc/firmware/modem.b08:system/etc/firmware/modem.b08 \
    vendor/sony/tianchi/proprietary/etc/firmware/modem.b10:system/etc/firmware/modem.b10 \
    vendor/sony/tianchi/proprietary/etc/firmware/modem.b11:system/etc/firmware/modem.b11 \
    vendor/sony/tianchi/proprietary/etc/firmware/modem.b13:system/etc/firmware/modem.b13 \
    vendor/sony/tianchi/proprietary/etc/firmware/modem.b14:system/etc/firmware/modem.b14 \
    vendor/sony/tianchi/proprietary/etc/firmware/modem.b15:system/etc/firmware/modem.b15 \
    vendor/sony/tianchi/proprietary/etc/firmware/modem.b16:system/etc/firmware/modem.b16 \
    vendor/sony/tianchi/proprietary/etc/firmware/modem.b17:system/etc/firmware/modem.b17 \
    vendor/sony/tianchi/proprietary/etc/firmware/modem.b18:system/etc/firmware/modem.b18 \
    vendor/sony/tianchi/proprietary/etc/firmware/modem.b19:system/etc/firmware/modem.b19 \
    vendor/sony/tianchi/proprietary/etc/firmware/modem.b20:system/etc/firmware/modem.b20 \
    vendor/sony/tianchi/proprietary/etc/firmware/modem.b21:system/etc/firmware/modem.b21 \
    vendor/sony/tianchi/proprietary/etc/firmware/modem.b22:system/etc/firmware/modem.b22 \
    vendor/sony/tianchi/proprietary/etc/firmware/modem.b25:system/etc/firmware/modem.b25 \
    vendor/sony/tianchi/proprietary/etc/firmware/modem.b26:system/etc/firmware/modem.b26 \
    vendor/sony/tianchi/proprietary/etc/firmware/modem.b27:system/etc/firmware/modem.b27 \
    vendor/sony/tianchi/proprietary/etc/firmware/modem.mdt:system/etc/firmware/modem.mdt \
    vendor/sony/tianchi/proprietary/etc/firmware/tzhdcp.b00:system/etc/firmware/tzhdcp.b00 \
    vendor/sony/tianchi/proprietary/etc/firmware/tzhdcp.b01:system/etc/firmware/tzhdcp.b01 \
    vendor/sony/tianchi/proprietary/etc/firmware/tzhdcp.b02:system/etc/firmware/tzhdcp.b02 \
    vendor/sony/tianchi/proprietary/etc/firmware/tzhdcp.b03:system/etc/firmware/tzhdcp.b03 \
    vendor/sony/tianchi/proprietary/etc/firmware/tzhdcp.mdt:system/etc/firmware/tzhdcp.mdt \
    vendor/sony/tianchi/proprietary/etc/firmware/tzlibasb.b00:system/etc/firmware/tzlibasb.b00 \
    vendor/sony/tianchi/proprietary/etc/firmware/tzlibasb.b01:system/etc/firmware/tzlibasb.b01 \
    vendor/sony/tianchi/proprietary/etc/firmware/tzlibasb.b02:system/etc/firmware/tzlibasb.b02 \
    vendor/sony/tianchi/proprietary/etc/firmware/tzlibasb.b03:system/etc/firmware/tzlibasb.b03 \
    vendor/sony/tianchi/proprietary/etc/firmware/tzlibasb.mdt:system/etc/firmware/tzlibasb.mdt \
    vendor/sony/tianchi/proprietary/etc/firmware/tzsuntory.b00:system/etc/firmware/tzsuntory.b00 \
    vendor/sony/tianchi/proprietary/etc/firmware/tzsuntory.b01:system/etc/firmware/tzsuntory.b01 \
    vendor/sony/tianchi/proprietary/etc/firmware/tzsuntory.b02:system/etc/firmware/tzsuntory.b02 \
    vendor/sony/tianchi/proprietary/etc/firmware/tzsuntory.b03:system/etc/firmware/tzsuntory.b03 \
    vendor/sony/tianchi/proprietary/etc/firmware/tzsuntory.mdt:system/etc/firmware/tzsuntory.mdt \
    vendor/sony/tianchi/proprietary/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    vendor/sony/tianchi/proprietary/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    vendor/sony/tianchi/proprietary/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    vendor/sony/tianchi/proprietary/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    vendor/sony/tianchi/proprietary/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    vendor/sony/tianchi/proprietary/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    vendor/sony/tianchi/proprietary/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt \
    vendor/sony/tianchi/proprietary/etc/firmware/wcnss.b00:system/etc/firmware/wcnss.b00 \
    vendor/sony/tianchi/proprietary/etc/firmware/wcnss.b01:system/etc/firmware/wcnss.b01 \
    vendor/sony/tianchi/proprietary/etc/firmware/wcnss.b02:system/etc/firmware/wcnss.b02 \
    vendor/sony/tianchi/proprietary/etc/firmware/wcnss.b04:system/etc/firmware/wcnss.b04 \
    vendor/sony/tianchi/proprietary/etc/firmware/wcnss.b06:system/etc/firmware/wcnss.b06 \
    vendor/sony/tianchi/proprietary/etc/firmware/wcnss.b07:system/etc/firmware/wcnss.b07 \
    vendor/sony/tianchi/proprietary/etc/firmware/wcnss.b08:system/etc/firmware/wcnss.b08 \
    vendor/sony/tianchi/proprietary/etc/firmware/wcnss.b09:system/etc/firmware/wcnss.b09 \
    vendor/sony/tianchi/proprietary/etc/firmware/wcnss.mdt:system/etc/firmware/wcnss.mdt \
    vendor/sony/tianchi/proprietary/vendor/firmware/libpn547_fw.so:system/vendor/firmware/libpn547_fw.so \
    vendor/sony/tianchi/proprietary/vendor/lib/hw/sensors.msm8226.so:system/vendor/lib/hw/sensors.msm8226.so \
    vendor/sony/tianchi/proprietary/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so \
    vendor/sony/tianchi/proprietary/vendor/lib/libsensor_reg.so:system/vendor/lib/libsensor_reg.so
