# Copyright (C) 2018-2019 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/pioneer/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/sony/pioneer

PRODUCT_COPY_FILES += \
    vendor/sony/pioneer/proprietary/vendor/bin/qns:$(TARGET_COPY_OUT_VENDOR)/bin/qns \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX219/120/ISO1400_3200x1808.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX219/120/ISO1400_3200x1808.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX219/120/ISO1400_3264x2448.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX219/120/ISO1400_3264x2448.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX219/120/ISO2000_3200x1808.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX219/120/ISO2000_3200x1808.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX219/120/ISO2000_3264x2448.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX219/120/ISO2000_3264x2448.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX219/120/ISO240_3200x1808.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX219/120/ISO240_3200x1808.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX219/120/ISO240_3264x2448.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX219/120/ISO240_3264x2448.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX219/120/ISO3200_3200x1808.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX219/120/ISO3200_3200x1808.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX219/120/ISO3200_3264x2448.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX219/120/ISO3200_3264x2448.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX219/120/ISO400_3200x1808.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX219/120/ISO400_3200x1808.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX219/120/ISO400_3264x2448.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX219/120/ISO400_3264x2448.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX219/80/ISO1400_3200x1808.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX219/80/ISO1400_3200x1808.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX219/80/ISO1400_3264x2448.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX219/80/ISO1400_3264x2448.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX219/80/ISO2000_3200x1808.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX219/80/ISO2000_3200x1808.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX219/80/ISO2000_3264x2448.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX219/80/ISO2000_3264x2448.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX219/80/ISO240_3200x1808.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX219/80/ISO240_3200x1808.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX219/80/ISO240_3264x2448.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX219/80/ISO240_3264x2448.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX219/80/ISO3200_3200x1808.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX219/80/ISO3200_3200x1808.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX219/80/ISO3200_3264x2448.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX219/80/ISO3200_3264x2448.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX219/80/ISO400_3200x1808.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX219/80/ISO400_3200x1808.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX219/80/ISO400_3264x2448.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX219/80/ISO400_3264x2448.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX300/ISO11000_2592x1944.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX300/ISO11000_2592x1944.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX300/ISO11000_3200x1808.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX300/ISO11000_3200x1808.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX300/ISO2200_2592x1944.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX300/ISO2200_2592x1944.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX300/ISO2200_3200x1808.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX300/ISO2200_3200x1808.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX300/ISO240_4000x3008.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX300/ISO240_4000x3008.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX300/ISO240_4624x2608.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX300/ISO240_4624x2608.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX300/ISO240_5520x4144.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX300/ISO240_5520x4144.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX300/ISO240_5984x3376.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX300/ISO240_5984x3376.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX300/ISO3000_2592x1944.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX300/ISO3000_2592x1944.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX300/ISO3000_3200x1808.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX300/ISO3000_3200x1808.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX300/ISO4000_2592x1944.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX300/ISO4000_2592x1944.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX300/ISO4000_3200x1808.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX300/ISO4000_3200x1808.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX300/ISO400_4000x3008.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX300/ISO400_4000x3008.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX300/ISO400_4624x2608.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX300/ISO400_4624x2608.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX300/ISO400_5520x4144.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX300/ISO400_5520x4144.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX300/ISO400_5984x3376.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX300/ISO400_5984x3376.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX300/ISO520_4000x3008.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX300/ISO520_4000x3008.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX300/ISO520_4624x2608.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX300/ISO520_4624x2608.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX300/ISO520_5520x4144.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX300/ISO520_5520x4144.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX300/ISO520_5984x3376.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX300/ISO520_5984x3376.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX300/ISO6000_2592x1944.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX300/ISO6000_2592x1944.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX300/ISO6000_3200x1808.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX300/ISO6000_3200x1808.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX300/ISO7200_2592x1944.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX300/ISO7200_2592x1944.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX300/ISO7200_3200x1808.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX300/ISO7200_3200x1808.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX300/ISO9000_2592x1944.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX300/ISO9000_2592x1944.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/FLASH_ON/IMX300/ISO9000_3200x1808.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/FLASH_ON/IMX300/ISO9000_3200x1808.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX219/120/ISO1400_3200x1808.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX219/120/ISO1400_3200x1808.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX219/120/ISO1400_3264x2448.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX219/120/ISO1400_3264x2448.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX219/120/ISO2000_3200x1808.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX219/120/ISO2000_3200x1808.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX219/120/ISO2000_3264x2448.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX219/120/ISO2000_3264x2448.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX219/120/ISO240_3200x1808.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX219/120/ISO240_3200x1808.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX219/120/ISO240_3264x2448.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX219/120/ISO240_3264x2448.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX219/120/ISO3200_3200x1808.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX219/120/ISO3200_3200x1808.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX219/120/ISO3200_3264x2448.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX219/120/ISO3200_3264x2448.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX219/120/ISO400_3200x1808.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX219/120/ISO400_3200x1808.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX219/120/ISO400_3264x2448.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX219/120/ISO400_3264x2448.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX219/80/ISO1400_3200x1808.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX219/80/ISO1400_3200x1808.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX219/80/ISO1400_3264x2448.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX219/80/ISO1400_3264x2448.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX219/80/ISO2000_3200x1808.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX219/80/ISO2000_3200x1808.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX219/80/ISO2000_3264x2448.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX219/80/ISO2000_3264x2448.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX219/80/ISO240_3200x1808.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX219/80/ISO240_3200x1808.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX219/80/ISO240_3264x2448.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX219/80/ISO240_3264x2448.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX219/80/ISO3200_3200x1808.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX219/80/ISO3200_3200x1808.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX219/80/ISO3200_3264x2448.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX219/80/ISO3200_3264x2448.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX219/80/ISO400_3200x1808.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX219/80/ISO400_3200x1808.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX219/80/ISO400_3264x2448.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX219/80/ISO400_3264x2448.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX300/ISO11000_2592x1944.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX300/ISO11000_2592x1944.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX300/ISO11000_3200x1808.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX300/ISO11000_3200x1808.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX300/ISO2200_2592x1944.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX300/ISO2200_2592x1944.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX300/ISO2200_3200x1808.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX300/ISO2200_3200x1808.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX300/ISO240_4000x3008.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX300/ISO240_4000x3008.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX300/ISO240_4624x2608.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX300/ISO240_4624x2608.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX300/ISO240_5520x4144.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX300/ISO240_5520x4144.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX300/ISO240_5984x3376.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX300/ISO240_5984x3376.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX300/ISO3000_2592x1944.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX300/ISO3000_2592x1944.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX300/ISO3000_3200x1808.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX300/ISO3000_3200x1808.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX300/ISO4000_2592x1944.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX300/ISO4000_2592x1944.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX300/ISO4000_3200x1808.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX300/ISO4000_3200x1808.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX300/ISO400_4000x3008.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX300/ISO400_4000x3008.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX300/ISO400_4624x2608.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX300/ISO400_4624x2608.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX300/ISO400_5520x4144.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX300/ISO400_5520x4144.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX300/ISO400_5984x3376.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX300/ISO400_5984x3376.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX300/ISO520_4000x3008.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX300/ISO520_4000x3008.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX300/ISO520_4624x2608.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX300/ISO520_4624x2608.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX300/ISO520_5520x4144.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX300/ISO520_5520x4144.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX300/ISO520_5984x3376.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX300/ISO520_5984x3376.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX300/ISO6000_2592x1944.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX300/ISO6000_2592x1944.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX300/ISO6000_3200x1808.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX300/ISO6000_3200x1808.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX300/ISO7200_2592x1944.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX300/ISO7200_2592x1944.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX300/ISO7200_3200x1808.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX300/ISO7200_3200x1808.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX300/ISO9000_2592x1944.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX300/ISO9000_2592x1944.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/IMX300/ISO9000_3200x1808.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/IMX300/ISO9000_3200x1808.ncf \
    vendor/sony/pioneer/proprietary/vendor/etc/acdbdata/Sony/Sony_ganges_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Sony/Sony_ganges_Bluetooth_cal.acdb \
    vendor/sony/pioneer/proprietary/vendor/etc/acdbdata/Sony/Sony_ganges_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Sony/Sony_ganges_General_cal.acdb \
    vendor/sony/pioneer/proprietary/vendor/etc/acdbdata/Sony/Sony_ganges_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Sony/Sony_ganges_Global_cal.acdb \
    vendor/sony/pioneer/proprietary/vendor/etc/acdbdata/Sony/Sony_ganges_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Sony/Sony_ganges_Handset_cal.acdb \
    vendor/sony/pioneer/proprietary/vendor/etc/acdbdata/Sony/Sony_ganges_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Sony/Sony_ganges_Hdmi_cal.acdb \
    vendor/sony/pioneer/proprietary/vendor/etc/acdbdata/Sony/Sony_ganges_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Sony/Sony_ganges_Headset_cal.acdb \
    vendor/sony/pioneer/proprietary/vendor/etc/acdbdata/Sony/Sony_ganges_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Sony/Sony_ganges_Speaker_cal.acdb \
    vendor/sony/pioneer/proprietary/vendor/etc/acdbdata/Sony/workspaceFile_Sony_ganges.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Sony/workspaceFile_Sony_ganges.qwsp \
    vendor/sony/pioneer/proprietary/vendor/etc/camera/imx219_chicony_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/imx219_chicony_chromatix.xml \
    vendor/sony/pioneer/proprietary/vendor/etc/camera/imx219_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/imx219_chromatix.xml \
    vendor/sony/pioneer/proprietary/vendor/etc/camera/imx300_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/imx300_chromatix.xml \
    vendor/sony/pioneer/proprietary/vendor/etc/camera/sm12_camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sm12_camera_config.xml \
    vendor/sony/pioneer/proprietary/vendor/etc/qdcm_calib_data_5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_5.xml \
    vendor/sony/pioneer/proprietary/vendor/etc/sensors/sensor_def_somc_platform.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sensor_def_somc_platform.conf \
    vendor/sony/pioneer/proprietary/vendor/etc/sensors/sensor_def_somc_product.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sensor_def_somc_product.conf \
    vendor/sony/pioneer/proprietary/vendor/etc/wifi/bdwlan.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bdwlan.bin \
    vendor/sony/pioneer/proprietary/vendor/firmware/bu64747gwz.coeff:$(TARGET_COPY_OUT_VENDOR)/firmware/bu64747gwz.coeff \
    vendor/sony/pioneer/proprietary/vendor/firmware/bu64747gwz.prog:$(TARGET_COPY_OUT_VENDOR)/firmware/bu64747gwz.prog \
    vendor/sony/pioneer/proprietary/vendor/lib/libactuator_bu64747gwz.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_bu64747gwz.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx219_chicony_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_chicony_common.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx219_chicony_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_chicony_cpp_snapshot.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx219_chicony_cpp_snapshot_B.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_chicony_cpp_snapshot_B.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx219_chicony_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_chicony_cpp_video.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx219_chicony_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_chicony_postproc.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx219_chicony_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_chicony_snapshot.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx219_chicony_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_chicony_video.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx219_chicony_zsl_preview_3rd_lc898122.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_chicony_zsl_preview_3rd_lc898122.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx219_chicony_zsl_preview_lc898122.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_chicony_zsl_preview_lc898122.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx219_chicony_zsl_video_lc898122.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_chicony_zsl_video_lc898122.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx219_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_cpp_snapshot.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx219_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_cpp_video.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx219_sm42_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_sm42_common.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx219_sm42_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_sm42_cpp_snapshot.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx219_sm42_cpp_snapshot_B.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_sm42_cpp_snapshot_B.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx219_sm42_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_sm42_cpp_video.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx219_sm42_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_sm42_postproc.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx219_sm42_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_sm42_snapshot.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx219_sm42_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_sm42_video.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx219_sm42_zsl_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_sm42_zsl_preview.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx219_sm42_zsl_preview_3rd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_sm42_zsl_preview_3rd.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx219_sm42_zsl_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_sm42_zsl_video.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx300_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx300_cpp_snapshot.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx300_sm42_4K_panorama.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx300_sm42_4K_panorama.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx300_sm42_4K_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx300_sm42_4K_preview.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx300_sm42_4K_video_hdr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx300_sm42_4K_video_hdr.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx300_sm42_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx300_sm42_common.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx300_sm42_common_old.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx300_sm42_common_old.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx300_sm42_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx300_sm42_cpp_snapshot.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx300_sm42_cpp_snapshot_B.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx300_sm42_cpp_snapshot_B.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx300_sm42_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx300_sm42_cpp_video.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx300_sm42_cpp_video_hdr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx300_sm42_cpp_video_hdr.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx300_sm42_hfr_120_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx300_sm42_hfr_120_3a.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx300_sm42_hfr_60_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx300_sm42_hfr_60_3a.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx300_sm42_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx300_sm42_postproc.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx300_sm42_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx300_sm42_snapshot.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx300_sm42_snapshot_quick.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx300_sm42_snapshot_quick.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx300_sm42_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx300_sm42_video.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx300_sm42_video_hdr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx300_sm42_video_hdr.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx300_sm42_zsl_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx300_sm42_zsl_preview.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx300_sm42_zsl_preview_20m.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx300_sm42_zsl_preview_20m.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx300_sm42_zsl_preview_20m_3rd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx300_sm42_zsl_preview_20m_3rd.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx300_sm42_zsl_preview_20m_manual.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx300_sm42_zsl_preview_20m_manual.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx300_sm42_zsl_preview_20m_quick.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx300_sm42_zsl_preview_20m_quick.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx300_sm42_zsl_preview_3rd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx300_sm42_zsl_preview_3rd.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx300_sm42_zsl_preview_manual.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx300_sm42_zsl_preview_manual.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx300_sm42_zsl_preview_quick.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx300_sm42_zsl_preview_quick.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx300_sm42_zsl_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx300_sm42_zsl_video.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libchromatix_imx300_sm42_zsl_video_hdr_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx300_sm42_zsl_video_hdr_3a.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_sensor_modules.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libmmcamera_imx219.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imx219.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libmmcamera_imx219_chicony.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imx219_chicony.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libmmcamera_imx300.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imx300.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libmmcamera_sony_imx219_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_sony_imx219_eeprom.so \
    vendor/sony/pioneer/proprietary/vendor/lib/libmmcamera_sony_imx300_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_sony_imx300_eeprom.so
