# Copyright (C) 2011-2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/z3c/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/sony/z3c/proprietary/etc/acdbdata/Handset_cal.acdb:system/etc/acdbdata/Handset_cal.acdb \
    vendor/sony/z3c/proprietary/etc/acdbdata/Speaker_cal.acdb:system/etc/acdbdata/Speaker_cal.acdb \
    vendor/sony/z3c/proprietary/etc/firmware/adsp.b00:system/etc/firmware/adsp.b00 \
    vendor/sony/z3c/proprietary/etc/firmware/adsp.b01:system/etc/firmware/adsp.b01 \
    vendor/sony/z3c/proprietary/etc/firmware/adsp.b02:system/etc/firmware/adsp.b02 \
    vendor/sony/z3c/proprietary/etc/firmware/adsp.b03:system/etc/firmware/adsp.b03 \
    vendor/sony/z3c/proprietary/etc/firmware/adsp.b04:system/etc/firmware/adsp.b04 \
    vendor/sony/z3c/proprietary/etc/firmware/adsp.b05:system/etc/firmware/adsp.b05 \
    vendor/sony/z3c/proprietary/etc/firmware/adsp.b06:system/etc/firmware/adsp.b06 \
    vendor/sony/z3c/proprietary/etc/firmware/adsp.b07:system/etc/firmware/adsp.b07 \
    vendor/sony/z3c/proprietary/etc/firmware/adsp.b08:system/etc/firmware/adsp.b08 \
    vendor/sony/z3c/proprietary/etc/firmware/adsp.b09:system/etc/firmware/adsp.b09 \
    vendor/sony/z3c/proprietary/etc/firmware/adsp.b10:system/etc/firmware/adsp.b10 \
    vendor/sony/z3c/proprietary/etc/firmware/adsp.b11:system/etc/firmware/adsp.b11 \
    vendor/sony/z3c/proprietary/etc/firmware/adsp.b12:system/etc/firmware/adsp.b12 \
    vendor/sony/z3c/proprietary/etc/firmware/adsp.mdt:system/etc/firmware/adsp.mdt \
    vendor/sony/z3c/proprietary/etc/firmware/mba.b00:system/etc/firmware/mba.b00 \
    vendor/sony/z3c/proprietary/etc/firmware/mba.mdt:system/etc/firmware/mba.mdt \
    vendor/sony/z3c/proprietary/etc/firmware/modem.b00:system/etc/firmware/modem.b00 \
    vendor/sony/z3c/proprietary/etc/firmware/modem.b01:system/etc/firmware/modem.b01 \
    vendor/sony/z3c/proprietary/etc/firmware/modem.b02:system/etc/firmware/modem.b02 \
    vendor/sony/z3c/proprietary/etc/firmware/modem.b03:system/etc/firmware/modem.b03 \
    vendor/sony/z3c/proprietary/etc/firmware/modem.b06:system/etc/firmware/modem.b06 \
    vendor/sony/z3c/proprietary/etc/firmware/modem.b08:system/etc/firmware/modem.b08 \
    vendor/sony/z3c/proprietary/etc/firmware/modem.b09:system/etc/firmware/modem.b09 \
    vendor/sony/z3c/proprietary/etc/firmware/modem.b11:system/etc/firmware/modem.b11 \
    vendor/sony/z3c/proprietary/etc/firmware/modem.b12:system/etc/firmware/modem.b12 \
    vendor/sony/z3c/proprietary/etc/firmware/modem.b13:system/etc/firmware/modem.b13 \
    vendor/sony/z3c/proprietary/etc/firmware/modem.b14:system/etc/firmware/modem.b14 \
    vendor/sony/z3c/proprietary/etc/firmware/modem.b15:system/etc/firmware/modem.b15 \
    vendor/sony/z3c/proprietary/etc/firmware/modem.b16:system/etc/firmware/modem.b16 \
    vendor/sony/z3c/proprietary/etc/firmware/modem.b17:system/etc/firmware/modem.b17 \
    vendor/sony/z3c/proprietary/etc/firmware/modem.b18:system/etc/firmware/modem.b18 \
    vendor/sony/z3c/proprietary/etc/firmware/modem.b19:system/etc/firmware/modem.b19 \
    vendor/sony/z3c/proprietary/etc/firmware/modem.b22:system/etc/firmware/modem.b22 \
    vendor/sony/z3c/proprietary/etc/firmware/modem.b23:system/etc/firmware/modem.b23 \
    vendor/sony/z3c/proprietary/etc/firmware/modem.b24:system/etc/firmware/modem.b24 \
    vendor/sony/z3c/proprietary/etc/firmware/modem.b25:system/etc/firmware/modem.b25 \
    vendor/sony/z3c/proprietary/etc/firmware/modem.mdt:system/etc/firmware/modem.mdt \
    vendor/sony/z3c/proprietary/etc/firmware/tzhdcp.b00:system/etc/firmware/tzhdcp.b00 \
    vendor/sony/z3c/proprietary/etc/firmware/tzhdcp.b01:system/etc/firmware/tzhdcp.b01 \
    vendor/sony/z3c/proprietary/etc/firmware/tzhdcp.b02:system/etc/firmware/tzhdcp.b02 \
    vendor/sony/z3c/proprietary/etc/firmware/tzhdcp.b03:system/etc/firmware/tzhdcp.b03 \
    vendor/sony/z3c/proprietary/etc/firmware/tzhdcp.mdt:system/etc/firmware/tzhdcp.mdt \
    vendor/sony/z3c/proprietary/etc/tfa98xx/FMSpeaker_btm.eq:system/etc/tfa98xx/FMSpeaker_btm.eq \
    vendor/sony/z3c/proprietary/etc/tfa98xx/FMSpeaker_btm.preset:system/etc/tfa98xx/FMSpeaker_btm.preset \
    vendor/sony/z3c/proprietary/etc/tfa98xx/FMSpeaker_top.eq:system/etc/tfa98xx/FMSpeaker_top.eq \
    vendor/sony/z3c/proprietary/etc/tfa98xx/FMSpeaker_top.preset:system/etc/tfa98xx/FMSpeaker_top.preset \
    vendor/sony/z3c/proprietary/etc/tfa98xx/HiFiSpeakerRing_btm.eq:system/etc/tfa98xx/HiFiSpeakerRing_btm.eq \
    vendor/sony/z3c/proprietary/etc/tfa98xx/HiFiSpeakerRing_btm.preset:system/etc/tfa98xx/HiFiSpeakerRing_btm.preset \
    vendor/sony/z3c/proprietary/etc/tfa98xx/HiFiSpeakerRing_top.eq:system/etc/tfa98xx/HiFiSpeakerRing_top.eq \
    vendor/sony/z3c/proprietary/etc/tfa98xx/HiFiSpeakerRing_top.preset:system/etc/tfa98xx/HiFiSpeakerRing_top.preset \
    vendor/sony/z3c/proprietary/etc/tfa98xx/HiFiSpeakerSforce_btm.eq:system/etc/tfa98xx/HiFiSpeakerSforce_btm.eq \
    vendor/sony/z3c/proprietary/etc/tfa98xx/HiFiSpeakerSforce_btm.preset:system/etc/tfa98xx/HiFiSpeakerSforce_btm.preset \
    vendor/sony/z3c/proprietary/etc/tfa98xx/HiFiSpeakerSforce_top.eq:system/etc/tfa98xx/HiFiSpeakerSforce_top.eq \
    vendor/sony/z3c/proprietary/etc/tfa98xx/HiFiSpeakerSforce_top.preset:system/etc/tfa98xx/HiFiSpeakerSforce_top.preset \
    vendor/sony/z3c/proprietary/etc/tfa98xx/HiFiSpeaker_btm.eq:system/etc/tfa98xx/HiFiSpeaker_btm.eq \
    vendor/sony/z3c/proprietary/etc/tfa98xx/HiFiSpeaker_btm.preset:system/etc/tfa98xx/HiFiSpeaker_btm.preset \
    vendor/sony/z3c/proprietary/etc/tfa98xx/HiFiSpeaker_top.eq:system/etc/tfa98xx/HiFiSpeaker_top.eq \
    vendor/sony/z3c/proprietary/etc/tfa98xx/HiFiSpeaker_top.preset:system/etc/tfa98xx/HiFiSpeaker_top.preset \
    vendor/sony/z3c/proprietary/etc/tfa98xx/TFA9890.patch:system/etc/tfa98xx/TFA9890.patch \
    vendor/sony/z3c/proprietary/etc/tfa98xx/TFA9890_Receiver.config:system/etc/tfa98xx/TFA9890_Receiver.config \
    vendor/sony/z3c/proprietary/etc/tfa98xx/TFA9890_btm.config:system/etc/tfa98xx/TFA9890_btm.config \
    vendor/sony/z3c/proprietary/etc/tfa98xx/TFA9890_top.config:system/etc/tfa98xx/TFA9890_top.config \
    vendor/sony/z3c/proprietary/etc/tfa98xx/VoiceCallEarpice_top.eq:system/etc/tfa98xx/VoiceCallEarpice_top.eq \
    vendor/sony/z3c/proprietary/etc/tfa98xx/VoiceCallEarpice_top.preset:system/etc/tfa98xx/VoiceCallEarpice_top.preset \
    vendor/sony/z3c/proprietary/etc/tfa98xx/VoiceCallSpeaker_btm.eq:system/etc/tfa98xx/VoiceCallSpeaker_btm.eq \
    vendor/sony/z3c/proprietary/etc/tfa98xx/VoiceCallSpeaker_btm.preset:system/etc/tfa98xx/VoiceCallSpeaker_btm.preset \
    vendor/sony/z3c/proprietary/etc/tfa98xx/VoiceCallSpeaker_top.eq:system/etc/tfa98xx/VoiceCallSpeaker_top.eq \
    vendor/sony/z3c/proprietary/etc/tfa98xx/VoiceCallSpeaker_top.preset:system/etc/tfa98xx/VoiceCallSpeaker_top.preset \
    vendor/sony/z3c/proprietary/etc/tfa98xx/btm.speaker:system/etc/tfa98xx/btm.speaker \
    vendor/sony/z3c/proprietary/etc/tfa98xx/coldboot.patch:system/etc/tfa98xx/coldboot.patch \
    vendor/sony/z3c/proprietary/etc/tfa98xx/top.speaker:system/etc/tfa98xx/top.speaker \
    vendor/sony/z3c/proprietary/usr/idc/clearpad.idc:system/usr/idc/clearpad.idc \
    vendor/sony/z3c/proprietary/vendor/firmware/fw_bcmdhd.bin:system/vendor/firmware/fw_bcmdhd.bin \
    vendor/sony/z3c/proprietary/vendor/firmware/fw_bcmdhd_apsta.bin:system/vendor/firmware/fw_bcmdhd_apsta.bin \
    vendor/sony/z3c/proprietary/vendor/lib/libactuator_bu64296gwx.so:system/vendor/lib/libactuator_bu64296gwx.so \
    vendor/sony/z3c/proprietary/vendor/lib/libactuator_bu64296gwx_camcorder.so:system/vendor/lib/libactuator_bu64296gwx_camcorder.so \
    vendor/sony/z3c/proprietary/vendor/lib/libactuator_bu64296gwx_camera.so:system/vendor/lib/libactuator_bu64296gwx_camera.so \
    vendor/sony/z3c/proprietary/vendor/lib/libchromatix_imx132_common.so:system/vendor/lib/libchromatix_imx132_common.so \
    vendor/sony/z3c/proprietary/vendor/lib/libchromatix_imx132_cpp_liveshot.so:system/vendor/lib/libchromatix_imx132_cpp_liveshot.so \
    vendor/sony/z3c/proprietary/vendor/lib/libchromatix_imx132_cpp_preview.so:system/vendor/lib/libchromatix_imx132_cpp_preview.so \
    vendor/sony/z3c/proprietary/vendor/lib/libchromatix_imx132_cpp_snapshot.so:system/vendor/lib/libchromatix_imx132_cpp_snapshot.so \
    vendor/sony/z3c/proprietary/vendor/lib/libchromatix_imx132_cpp_video.so:system/vendor/lib/libchromatix_imx132_cpp_video.so \
    vendor/sony/z3c/proprietary/vendor/lib/libchromatix_imx132_default_video.so:system/vendor/lib/libchromatix_imx132_default_video.so \
    vendor/sony/z3c/proprietary/vendor/lib/libchromatix_imx132_liveshot.so:system/vendor/lib/libchromatix_imx132_liveshot.so \
    vendor/sony/z3c/proprietary/vendor/lib/libchromatix_imx132_postproc.so:system/vendor/lib/libchromatix_imx132_postproc.so \
    vendor/sony/z3c/proprietary/vendor/lib/libchromatix_imx132_preview.so:system/vendor/lib/libchromatix_imx132_preview.so \
    vendor/sony/z3c/proprietary/vendor/lib/libchromatix_imx132_snapshot.so:system/vendor/lib/libchromatix_imx132_snapshot.so \
    vendor/sony/z3c/proprietary/vendor/lib/libchromatix_imx200_common.so:system/vendor/lib/libchromatix_imx200_common.so \
    vendor/sony/z3c/proprietary/vendor/lib/libchromatix_imx200_cpp_hfr_120.so:system/vendor/lib/libchromatix_imx200_cpp_hfr_120.so \
    vendor/sony/z3c/proprietary/vendor/lib/libchromatix_imx200_cpp_hfr_60.so:system/vendor/lib/libchromatix_imx200_cpp_hfr_60.so \
    vendor/sony/z3c/proprietary/vendor/lib/libchromatix_imx200_cpp_hfr_90.so:system/vendor/lib/libchromatix_imx200_cpp_hfr_90.so \
    vendor/sony/z3c/proprietary/vendor/lib/libchromatix_imx200_cpp_liveshot.so:system/vendor/lib/libchromatix_imx200_cpp_liveshot.so \
    vendor/sony/z3c/proprietary/vendor/lib/libchromatix_imx200_cpp_preview.so:system/vendor/lib/libchromatix_imx200_cpp_preview.so \
    vendor/sony/z3c/proprietary/vendor/lib/libchromatix_imx200_cpp_snapshot.so:system/vendor/lib/libchromatix_imx200_cpp_snapshot.so \
    vendor/sony/z3c/proprietary/vendor/lib/libchromatix_imx200_cpp_snapshot_hdr.so:system/vendor/lib/libchromatix_imx200_cpp_snapshot_hdr.so \
    vendor/sony/z3c/proprietary/vendor/lib/libchromatix_imx200_cpp_video.so:system/vendor/lib/libchromatix_imx200_cpp_video.so \
    vendor/sony/z3c/proprietary/vendor/lib/libchromatix_imx200_cpp_video_4k.so:system/vendor/lib/libchromatix_imx200_cpp_video_4k.so \
    vendor/sony/z3c/proprietary/vendor/lib/libchromatix_imx200_cpp_video_hdr.so:system/vendor/lib/libchromatix_imx200_cpp_video_hdr.so \
    vendor/sony/z3c/proprietary/vendor/lib/libchromatix_imx200_default_video.so:system/vendor/lib/libchromatix_imx200_default_video.so \
    vendor/sony/z3c/proprietary/vendor/lib/libchromatix_imx200_hfr_120.so:system/vendor/lib/libchromatix_imx200_hfr_120.so \
    vendor/sony/z3c/proprietary/vendor/lib/libchromatix_imx200_hfr_60.so:system/vendor/lib/libchromatix_imx200_hfr_60.so \
    vendor/sony/z3c/proprietary/vendor/lib/libchromatix_imx200_hfr_90.so:system/vendor/lib/libchromatix_imx200_hfr_90.so \
    vendor/sony/z3c/proprietary/vendor/lib/libchromatix_imx200_liveshot.so:system/vendor/lib/libchromatix_imx200_liveshot.so \
    vendor/sony/z3c/proprietary/vendor/lib/libchromatix_imx200_postproc.so:system/vendor/lib/libchromatix_imx200_postproc.so \
    vendor/sony/z3c/proprietary/vendor/lib/libchromatix_imx200_preview.so:system/vendor/lib/libchromatix_imx200_preview.so \
    vendor/sony/z3c/proprietary/vendor/lib/libchromatix_imx200_snapshot.so:system/vendor/lib/libchromatix_imx200_snapshot.so \
    vendor/sony/z3c/proprietary/vendor/lib/libchromatix_imx200_snapshot_hdr.so:system/vendor/lib/libchromatix_imx200_snapshot_hdr.so \
    vendor/sony/z3c/proprietary/vendor/lib/libchromatix_imx200_video_4k.so:system/vendor/lib/libchromatix_imx200_video_4k.so \
    vendor/sony/z3c/proprietary/vendor/lib/libchromatix_imx200_video_hdr.so:system/vendor/lib/libchromatix_imx200_video_hdr.so \
    vendor/sony/z3c/proprietary/vendor/lib/libmmcamera_imx132.so:system/vendor/lib/libmmcamera_imx132.so \
    vendor/sony/z3c/proprietary/vendor/lib/libmmcamera_imx200.so:system/vendor/lib/libmmcamera_imx200.so
