# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/nanhu/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES := \
    vendor/sony/nanhu/proprietary/lib/libaudioalsa.so:obj/lib/libaudioalsa.so

PRODUCT_COPY_FILES += \
    vendor/sony/nanhu/proprietary/bin/updatemiscta:system/bin/updatemiscta \
    vendor/sony/nanhu/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/sony/nanhu/proprietary/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
    vendor/sony/nanhu/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/sony/nanhu/proprietary/bin/hciattach:system/bin/hciattach \
    vendor/sony/nanhu/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/sony/nanhu/proprietary/bin/cnd:system/bin/cnd \
    vendor/sony/nanhu/proprietary/bin/gpu_dcvsd:system/bin/gpu_dcvsd \
    vendor/sony/nanhu/proprietary/bin/nvcustomizer:system/bin/nvcustomizer \
    vendor/sony/nanhu/proprietary/bin/thermald:system/bin/thermald \
    vendor/sony/nanhu/proprietary/bin/wiperiface:system/bin/wiperiface \
    vendor/sony/nanhu/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/sony/nanhu/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/sony/nanhu/proprietary/etc/firmware/ath6k/AR6003/hw2.1.1/softmac:system/etc/firmware/ath6k/AR6003/hw2.1.1/softmac \
    vendor/sony/nanhu/proprietary/etc/firmware/ath6k/AR6003/hw2.1.1/bdata.bin:system/etc/firmware/ath6k/AR6003/hw2.1.1/bdata.bin \
    vendor/sony/nanhu/proprietary/etc/firmware/ath6k/AR6003/hw2.1.1/fw-4.bin:system/etc/firmware/ath6k/AR6003/hw2.1.1/fw-4.bin \
    vendor/sony/nanhu/proprietary/lib/libmmcamera_interface2.so:system/lib/libmmcamera_interface2.so \
    vendor/sony/nanhu/proprietary/lib/libutils.so:system/lib/libutils.so \
    vendor/sony/nanhu/proprietary/lib/liboem_rapi.so:system/lib/liboem_rapi.so \
    vendor/sony/nanhu/proprietary/lib/libdivxdrmdecrypt.so:system/lib/libdivxdrmdecrypt.so \
    vendor/sony/nanhu/proprietary/lib/libchromatix_ov5647_video_hfr.so:system/lib/libchromatix_ov5647_video_hfr.so \
    vendor/sony/nanhu/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/sony/nanhu/proprietary/lib/libchromatix_imx074_zsl.so:system/lib/libchromatix_imx074_zsl.so \
    vendor/sony/nanhu/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/sony/nanhu/proprietary/lib/libmmcamera_hdr_lib.so:system/lib/libmmcamera_hdr_lib.so \
    vendor/sony/nanhu/proprietary/lib/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
    vendor/sony/nanhu/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    vendor/sony/nanhu/proprietary/lib/libchromatix_ov2720_default_video.so:system/lib/libchromatix_ov2720_default_video.so \
    vendor/sony/nanhu/proprietary/lib/libloc_adapter.so:system/lib/libloc_adapter.so \
    vendor/sony/nanhu/proprietary/lib/libchromatix_s5k4e1_default_video.so:system/lib/libchromatix_s5k4e1_default_video.so \
    vendor/sony/nanhu/proprietary/lib/libchromatix_ov5647_default_video.so:system/lib/libchromatix_ov5647_default_video.so \
    vendor/sony/nanhu/proprietary/lib/libchromatix_imx074_preview.so:system/lib/libchromatix_imx074_preview.so \
    vendor/sony/nanhu/proprietary/lib/libcneqmiutils.so:system/lib/libcneqmiutils.so \
    vendor/sony/nanhu/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/sony/nanhu/proprietary/lib/libchromatix_mt9e013_video_hfr.so:system/lib/libchromatix_mt9e013_video_hfr.so \
    vendor/sony/nanhu/proprietary/lib/libchromatix_s5k3l1yx_hfr_120fps.so:system/lib/libchromatix_s5k3l1yx_hfr_120fps.so \
    vendor/sony/nanhu/proprietary/lib/libchromatix_s5k3l1yx_default_video.so:system/lib/libchromatix_s5k3l1yx_default_video.so \
    vendor/sony/nanhu/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/sony/nanhu/proprietary/lib/libcommondefs.so:system/lib/libcommondefs.so \
    vendor/sony/nanhu/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/sony/nanhu/proprietary/lib/libloc_api-rpc-qc.so:system/lib/libloc_api-rpc-qc.so \
    vendor/sony/nanhu/proprietary/lib/libchromatix_imx091_default_video.so:system/lib/libchromatix_imx091_default_video.so \
    vendor/sony/nanhu/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/sony/nanhu/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/sony/nanhu/proprietary/lib/liballjoyn.so:system/lib/liballjoyn.so \
    vendor/sony/nanhu/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
    vendor/sony/nanhu/proprietary/lib/libmmcamera_image_stab.so:system/lib/libmmcamera_image_stab.so \
    vendor/sony/nanhu/proprietary/lib/libcm.so:system/lib/libcm.so \
    vendor/sony/nanhu/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/sony/nanhu/proprietary/lib/libOmxAacEnc.so:system/lib/libOmxAacEnc.so \
    vendor/sony/nanhu/proprietary/lib/libOmxWmaDec.so:system/lib/libOmxWmaDec.so \
    vendor/sony/nanhu/proprietary/lib/libchromatix_s5k3l1yx_hfr_60fps.so:system/lib/libchromatix_s5k3l1yx_hfr_60fps.so \
    vendor/sony/nanhu/proprietary/lib/libmmcamera_wavelet_lib.so:system/lib/libmmcamera_wavelet_lib.so \
    vendor/sony/nanhu/proprietary/lib/libqmi_client_qmux.so:system/lib/libqmi_client_qmux.so \
    vendor/sony/nanhu/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/sony/nanhu/proprietary/lib/libOmxQcelp13Dec.so:system/lib/libOmxQcelp13Dec.so \
    vendor/sony/nanhu/proprietary/lib/libOmxMp3Dec.so:system/lib/libOmxMp3Dec.so \
    vendor/sony/nanhu/proprietary/lib/libOmxrv9Dec.so:system/lib/libOmxrv9Dec.so \
    vendor/sony/nanhu/proprietary/lib/libmmcamera_statsproc31.so:system/lib/libmmcamera_statsproc31.so \
    vendor/sony/nanhu/proprietary/lib/libchromatix_ov9726_default_video.so:system/lib/libchromatix_ov9726_default_video.so \
    vendor/sony/nanhu/proprietary/lib/libchromatix_s5k3l1yx_zsl.so:system/lib/libchromatix_s5k3l1yx_zsl.so \
    vendor/sony/nanhu/proprietary/lib/libgemini.so:system/lib/libgemini.so \
    vendor/sony/nanhu/proprietary/lib/libchromatix_mt9e013_default_video.so:system/lib/libchromatix_mt9e013_default_video.so \
    vendor/sony/nanhu/proprietary/lib/libchromatix_ov5647_preview.so:system/lib/libchromatix_ov5647_preview.so \
    vendor/sony/nanhu/proprietary/lib/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
    vendor/sony/nanhu/proprietary/lib/libcneapiclient.so:system/lib/libcneapiclient.so \
    vendor/sony/nanhu/proprietary/lib/libchromatix_ov2720_zsl.so:system/lib/libchromatix_ov2720_zsl.so \
    vendor/sony/nanhu/proprietary/lib/libchromatix_ov9726_preview.so:system/lib/libchromatix_ov9726_preview.so \
    vendor/sony/nanhu/proprietary/lib/libOmxAmrRtpDec.so:system/lib/libOmxAmrRtpDec.so \
    vendor/sony/nanhu/proprietary/lib/libOmxAmrEnc.so:system/lib/libOmxAmrEnc.so \
    vendor/sony/nanhu/proprietary/lib/libmm-abl.so:system/lib/libmm-abl.so \
    vendor/sony/nanhu/proprietary/lib/libnv.so:system/lib/libnv.so \
    vendor/sony/nanhu/proprietary/lib/libmm-abl-oem.so:system/lib/libmm-abl-oem.so \
    vendor/sony/nanhu/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
    vendor/sony/nanhu/proprietary/lib/libchromatix_s5k3l1yx_preview.so:system/lib/libchromatix_s5k3l1yx_preview.so \
    vendor/sony/nanhu/proprietary/lib/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
    vendor/sony/nanhu/proprietary/lib/libOmxWmvDec.so:system/lib/libOmxWmvDec.so \
    vendor/sony/nanhu/proprietary/lib/libqdi.so:system/lib/libqdi.so \
    vendor/sony/nanhu/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/sony/nanhu/proprietary/lib/libOmxEvrcEnc.so:system/lib/libOmxEvrcEnc.so \
    vendor/sony/nanhu/proprietary/lib/libloc_eng.so:system/lib/libloc_eng.so \
    vendor/sony/nanhu/proprietary/lib/libOmxAmrDec.so:system/lib/libOmxAmrDec.so \
    vendor/sony/nanhu/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
    vendor/sony/nanhu/proprietary/lib/libOmxEvrcHwDec.so:system/lib/libOmxEvrcHwDec.so \
    vendor/sony/nanhu/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/sony/nanhu/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
    vendor/sony/nanhu/proprietary/lib/hw/camera.msm7x27a.so:system/lib/hw/camera.msm7x27a.so \
    vendor/sony/nanhu/proprietary/lib/libloc_ext.so:system/lib/libloc_ext.so \
    vendor/sony/nanhu/proprietary/lib/libauth.so:system/lib/libauth.so \
    vendor/sony/nanhu/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/sony/nanhu/proprietary/lib/libOmxVp8Dec.so:system/lib/libOmxVp8Dec.so \
    vendor/sony/nanhu/proprietary/lib/libmiscta.so:system/lib/libmiscta.so \
    vendor/sony/nanhu/proprietary/lib/libchromatix_imx091_preview.so:system/lib/libchromatix_imx091_preview.so \
    vendor/sony/nanhu/proprietary/lib/libqueue.so:system/lib/libqueue.so \
    vendor/sony/nanhu/proprietary/lib/libOmxIttiamVenc.so:system/lib/libOmxIttiamVenc.so \
    vendor/sony/nanhu/proprietary/lib/libchromatix_ov2720_hfr.so:system/lib/libchromatix_ov2720_hfr.so \
    vendor/sony/nanhu/proprietary/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
    vendor/sony/nanhu/proprietary/lib/libOmxAmrwbDec.so:system/lib/libOmxAmrwbDec.so \
    vendor/sony/nanhu/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/sony/nanhu/proprietary/lib/libchromatix_mt9e013_preview.so:system/lib/libchromatix_mt9e013_preview.so \
    vendor/sony/nanhu/proprietary/lib/libchromatix_imx074_video_hd.so:system/lib/libchromatix_imx074_video_hd.so \
    vendor/sony/nanhu/proprietary/lib/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
    vendor/sony/nanhu/proprietary/lib/libchromatix_s5k4e1_preview.so:system/lib/libchromatix_s5k4e1_preview.so \
    vendor/sony/nanhu/proprietary/lib/libchromatix_ov8825_default_video.so:system/lib/libchromatix_ov8825_default_video.so \
    vendor/sony/nanhu/proprietary/lib/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/sony/nanhu/proprietary/lib/libchromatix_s5k5ca_preview.so:system/lib/libchromatix_s5k5ca_preview.so \
    vendor/sony/nanhu/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/sony/nanhu/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/sony/nanhu/proprietary/lib/libaudioeq.so:system/lib/libaudioeq.so \
    vendor/sony/nanhu/proprietary/lib/libcneutils.so:system/lib/libcneutils.so \
    vendor/sony/nanhu/proprietary/lib/libOmxEvrcDec.so:system/lib/libOmxEvrcDec.so \
    vendor/sony/nanhu/proprietary/lib/libgps.utils.so:system/lib/libgps.utils.so \
    vendor/sony/nanhu/proprietary/lib/libchromatix_imx091_video_hd.so:system/lib/libchromatix_imx091_video_hd.so \
    vendor/sony/nanhu/proprietary/lib/libchromatix_imx074_default_video.so:system/lib/libchromatix_imx074_default_video.so \
    vendor/sony/nanhu/proprietary/lib/libchromatix_s5k3l1yx_video_hd.so:system/lib/libchromatix_s5k3l1yx_video_hd.so \
    vendor/sony/nanhu/proprietary/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
    vendor/sony/nanhu/proprietary/lib/libOmxIttiamVdec.so:system/lib/libOmxIttiamVdec.so \
    vendor/sony/nanhu/proprietary/lib/libOmxOn2Dec.so:system/lib/libOmxOn2Dec.so \
    vendor/sony/nanhu/proprietary/lib/libwmsts.so:system/lib/libwmsts.so \
    vendor/sony/nanhu/proprietary/lib/libOmxQcelpHwDec.so:system/lib/libOmxQcelpHwDec.so \
    vendor/sony/nanhu/proprietary/lib/libcamera_client.so:system/lib/libcamera_client.so \
    vendor/sony/nanhu/proprietary/lib/libchromatix_ov2720_preview.so:system/lib/libchromatix_ov2720_preview.so \
    vendor/sony/nanhu/proprietary/lib/libOmxAc3HwDec.so:system/lib/libOmxAc3HwDec.so \
    vendor/sony/nanhu/proprietary/lib/libOmxQcelp13Enc.so:system/lib/libOmxQcelp13Enc.so \
    vendor/sony/nanhu/proprietary/lib/libOmxAdpcmDec.so:system/lib/libOmxAdpcmDec.so \
    vendor/sony/nanhu/proprietary/lib/libchromatix_s5k3l1yx_hfr_90fps.so:system/lib/libchromatix_s5k3l1yx_hfr_90fps.so \
    vendor/sony/nanhu/proprietary/lib/libOmxAacDec.so:system/lib/libOmxAacDec.so \
    vendor/sony/nanhu/proprietary/lib/libchromatix_ov8825_preview.so:system/lib/libchromatix_ov8825_preview.so \
    vendor/sony/nanhu/proprietary/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
    vendor/sony/nanhu/proprietary/lib/libxml.so:system/lib/libxml.so \
    vendor/sony/nanhu/proprietary/lib/libwms.so:system/lib/libwms.so
