# Copyright (C) 2013-2016 The CyanogenMod Project
# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/pollux-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/sony/pollux-common/proprietary/bin/updatemiscta:system/bin/updatemiscta \
    vendor/sony/pollux-common/proprietary/etc/firmware/touch_module_id_0x3a.img:system/etc/firmware/touch_module_id_0x3a.img \
    vendor/sony/pollux-common/proprietary/etc/firmware/touch_module_id_0x3b.img:system/etc/firmware/touch_module_id_0x3b.img \
    vendor/sony/pollux-common/proprietary/etc/firmware/touch_module_id_0x4c.img:system/etc/firmware/touch_module_id_0x4c.img \
    vendor/sony/pollux-common/proprietary/etc/flashled_calc_parameters.cfg:system/etc/flashled_calc_parameters.cfg \
    vendor/sony/pollux-common/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
    vendor/sony/pollux-common/proprietary/lib/libcald_server.so:system/lib/libcald_server.so \
    vendor/sony/pollux-common/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/sony/pollux-common/proprietary/vendor/camera/LGI02BN0_IMX132.dat:system/vendor/camera/LGI02BN0_IMX132.dat \
    vendor/sony/pollux-common/proprietary/vendor/camera/LGI08BN2.dat:system/vendor/camera/LGI08BN2.dat \
    vendor/sony/pollux-common/proprietary/vendor/camera/SEM02BN0_IMX132.dat:system/vendor/camera/SEM02BN0_IMX132.dat \
    vendor/sony/pollux-common/proprietary/vendor/camera/flash.dat:system/vendor/camera/flash.dat \
    vendor/sony/pollux-common/proprietary/vendor/camera/product.dat:system/vendor/camera/product.dat

PRODUCT_COPY_FILES += \
    vendor/sony/pollux-common/proprietary/bin/efsks:system/bin/efsks \
    vendor/sony/pollux-common/proprietary/bin/qcks:system/bin/qcks
