# Copyright (C) 2011-2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/togari/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/sony/togari/proprietary/bin/chargemon:system/bin/chargemon \
    vendor/sony/togari/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
    vendor/sony/togari/proprietary/bin/updatemiscta:system/bin/updatemiscta \
    vendor/sony/togari/proprietary/etc/acdbdata/Liquid/Liquid_Handset_cal.acdb:system/etc/acdbdata/Liquid/Liquid_Handset_cal.acdb \
    vendor/sony/togari/proprietary/etc/acdbdata/Liquid/Liquid_Speaker_cal.acdb:system/etc/acdbdata/Liquid/Liquid_Speaker_cal.acdb \
    vendor/sony/togari/proprietary/etc/acdbdata/MTP/MTP_Handset_cal.acdb:system/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
    vendor/sony/togari/proprietary/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:system/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
    vendor/sony/togari/proprietary/etc/firmware/touch_chip_id_0x74_config_id_0x0011.bin:system/etc/firmware/touch_chip_id_0x74_config_id_0x0011.bin \
    vendor/sony/togari/proprietary/etc/firmware/touch_chip_id_0x74_config_id_0x0460.bin:system/etc/firmware/touch_chip_id_0x74_config_id_0x0460.bin \
    vendor/sony/togari/proprietary/etc/firmware/touch_chip_id_0x75_config_id_0x0010.bin:system/etc/firmware/touch_chip_id_0x75_config_id_0x0010.bin \
    vendor/sony/togari/proprietary/etc/firmware/touch_chip_id_0x75_config_id_0x0012.bin:system/etc/firmware/touch_chip_id_0x75_config_id_0x0012.bin \
    vendor/sony/togari/proprietary/etc/firmware/touch_chip_id_0x75_config_id_0x0013.bin:system/etc/firmware/touch_chip_id_0x75_config_id_0x0013.bin \
    vendor/sony/togari/proprietary/etc/firmware/touch_module_id_0x43.img:system/etc/firmware/touch_module_id_0x43.img \
    vendor/sony/togari/proprietary/etc/firmware/touch_module_id_0x44.img:system/etc/firmware/touch_module_id_0x44.img \
    vendor/sony/togari/proprietary/etc/sensor_def_qcomdev.conf:system/etc/sensor_def_qcomdev.conf \
    vendor/sony/togari/proprietary/etc/sensors_calib.conf:system/etc/sensors_calib.conf \
    vendor/sony/togari/proprietary/usr/idc/clearpad.idc:system/usr/idc/clearpad.idc \
    vendor/sony/togari/proprietary/usr/idc/max1187x_pen_0.idc:system/usr/idc/max1187x_pen_0.idc \
    vendor/sony/togari/proprietary/usr/idc/max1187x_touchscreen_0.idc:system/usr/idc/max1187x_touchscreen_0.idc \
    vendor/sony/togari/proprietary/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so
