# Copyright (C) 2011-2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/togari/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/sony/togari/proprietary/etc/acdbdata/Handset_cal.acdb:system/etc/acdbdata/Handset_cal.acdb \
    vendor/sony/togari/proprietary/etc/acdbdata/Speaker_cal.acdb:system/etc/acdbdata/Speaker_cal.acdb \
    vendor/sony/togari/proprietary/etc/firmware/modem.b00:system/etc/firmware/modem.b00 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b01:system/etc/firmware/modem.b01 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b02:system/etc/firmware/modem.b02 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b03:system/etc/firmware/modem.b03 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b04:system/etc/firmware/modem.b04 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b05:system/etc/firmware/modem.b05 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b08:system/etc/firmware/modem.b08 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b11:system/etc/firmware/modem.b11 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b13:system/etc/firmware/modem.b13 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b14:system/etc/firmware/modem.b14 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b15:system/etc/firmware/modem.b15 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b16:system/etc/firmware/modem.b16 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b17:system/etc/firmware/modem.b17 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b18:system/etc/firmware/modem.b18 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b19:system/etc/firmware/modem.b19 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b20:system/etc/firmware/modem.b20 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b21:system/etc/firmware/modem.b21 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b22:system/etc/firmware/modem.b22 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b25:system/etc/firmware/modem.b25 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b26:system/etc/firmware/modem.b26 \
    vendor/sony/togari/proprietary/etc/firmware/modem.mdt:system/etc/firmware/modem.mdt \
    vendor/sony/togari/proprietary/etc/firmware/touch_chip_id_0x74_config_id_0x0011.bin:system/etc/firmware/touch_chip_id_0x74_config_id_0x0011.bin \
    vendor/sony/togari/proprietary/etc/firmware/touch_chip_id_0x74_config_id_0x0460.bin:system/etc/firmware/touch_chip_id_0x74_config_id_0x0460.bin \
    vendor/sony/togari/proprietary/etc/firmware/touch_chip_id_0x75_config_id_0x0010.bin:system/etc/firmware/touch_chip_id_0x75_config_id_0x0010.bin \
    vendor/sony/togari/proprietary/etc/firmware/touch_chip_id_0x75_config_id_0x0012.bin:system/etc/firmware/touch_chip_id_0x75_config_id_0x0012.bin \
    vendor/sony/togari/proprietary/etc/firmware/touch_chip_id_0x75_config_id_0x0013.bin:system/etc/firmware/touch_chip_id_0x75_config_id_0x0013.bin \
    vendor/sony/togari/proprietary/etc/firmware/touch_module_id_0x43.img:system/etc/firmware/touch_module_id_0x43.img \
    vendor/sony/togari/proprietary/etc/firmware/touch_module_id_0x44.img:system/etc/firmware/touch_module_id_0x44.img \
    vendor/sony/togari/proprietary/usr/idc/clearpad.idc:system/usr/idc/clearpad.idc \
    vendor/sony/togari/proprietary/usr/idc/max1187x_pen_0.idc:system/usr/idc/max1187x_pen_0.idc \
    vendor/sony/togari/proprietary/usr/idc/max1187x_touchscreen_0.idc:system/usr/idc/max1187x_touchscreen_0.idc
