# Copyright (C) 2011-2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/amami/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/sony/amami/proprietary/etc/acdbdata/Handset_cal.acdb:system/etc/acdbdata/Handset_cal.acdb \
    vendor/sony/amami/proprietary/etc/acdbdata/Speaker_cal.acdb:system/etc/acdbdata/Speaker_cal.acdb \
    vendor/sony/amami/proprietary/etc/firmware/modem.b00:system/etc/firmware/modem.b00 \
    vendor/sony/amami/proprietary/etc/firmware/modem.b01:system/etc/firmware/modem.b01 \
    vendor/sony/amami/proprietary/etc/firmware/modem.b02:system/etc/firmware/modem.b02 \
    vendor/sony/amami/proprietary/etc/firmware/modem.b03:system/etc/firmware/modem.b03 \
    vendor/sony/amami/proprietary/etc/firmware/modem.b04:system/etc/firmware/modem.b04 \
    vendor/sony/amami/proprietary/etc/firmware/modem.b05:system/etc/firmware/modem.b05 \
    vendor/sony/amami/proprietary/etc/firmware/modem.b08:system/etc/firmware/modem.b08 \
    vendor/sony/amami/proprietary/etc/firmware/modem.b11:system/etc/firmware/modem.b11 \
    vendor/sony/amami/proprietary/etc/firmware/modem.b13:system/etc/firmware/modem.b13 \
    vendor/sony/amami/proprietary/etc/firmware/modem.b14:system/etc/firmware/modem.b14 \
    vendor/sony/amami/proprietary/etc/firmware/modem.b15:system/etc/firmware/modem.b15 \
    vendor/sony/amami/proprietary/etc/firmware/modem.b16:system/etc/firmware/modem.b16 \
    vendor/sony/amami/proprietary/etc/firmware/modem.b17:system/etc/firmware/modem.b17 \
    vendor/sony/amami/proprietary/etc/firmware/modem.b18:system/etc/firmware/modem.b18 \
    vendor/sony/amami/proprietary/etc/firmware/modem.b19:system/etc/firmware/modem.b19 \
    vendor/sony/amami/proprietary/etc/firmware/modem.b20:system/etc/firmware/modem.b20 \
    vendor/sony/amami/proprietary/etc/firmware/modem.b21:system/etc/firmware/modem.b21 \
    vendor/sony/amami/proprietary/etc/firmware/modem.b22:system/etc/firmware/modem.b22 \
    vendor/sony/amami/proprietary/etc/firmware/modem.b25:system/etc/firmware/modem.b25 \
    vendor/sony/amami/proprietary/etc/firmware/modem.b26:system/etc/firmware/modem.b26 \
    vendor/sony/amami/proprietary/etc/firmware/modem.mdt:system/etc/firmware/modem.mdt \
    vendor/sony/amami/proprietary/etc/firmware/touch_module_id_0x45.img:system/etc/firmware/touch_module_id_0x45.img \
    vendor/sony/amami/proprietary/etc/firmware/touch_module_id_0x48.img:system/etc/firmware/touch_module_id_0x48.img \
    vendor/sony/amami/proprietary/etc/firmware/touch_module_id_0x4d.img:system/etc/firmware/touch_module_id_0x4d.img \
    vendor/sony/amami/proprietary/etc/firmware/touch_module_id_0x4e.img:system/etc/firmware/touch_module_id_0x4e.img \
    vendor/sony/amami/proprietary/etc/firmware/touch_module_id_0x53.img:system/etc/firmware/touch_module_id_0x53.img \
    vendor/sony/amami/proprietary/etc/firmware/touch_module_id_0x54.img:system/etc/firmware/touch_module_id_0x54.img \
    vendor/sony/amami/proprietary/etc/firmware/touch_module_id_0x5d.img:system/etc/firmware/touch_module_id_0x5d.img \
    vendor/sony/amami/proprietary/usr/idc/clearpad.idc:system/usr/idc/clearpad.idc \
    vendor/sony/amami/proprietary/vendor/lib/libactuator_bu64296gwx.so:system/vendor/lib/libactuator_bu64296gwx.so \
    vendor/sony/amami/proprietary/vendor/lib/libactuator_bu64296gwx_camcorder.so:system/vendor/lib/libactuator_bu64296gwx_camcorder.so \
    vendor/sony/amami/proprietary/vendor/lib/libactuator_bu64296gwx_camera.so:system/vendor/lib/libactuator_bu64296gwx_camera.so \
    vendor/sony/amami/proprietary/vendor/lib/libchromatix_imx132_common.so:system/vendor/lib/libchromatix_imx132_common.so \
    vendor/sony/amami/proprietary/vendor/lib/libchromatix_imx132_cpp_liveshot.so:system/vendor/lib/libchromatix_imx132_cpp_liveshot.so \
    vendor/sony/amami/proprietary/vendor/lib/libchromatix_imx132_cpp_preview.so:system/vendor/lib/libchromatix_imx132_cpp_preview.so \
    vendor/sony/amami/proprietary/vendor/lib/libchromatix_imx132_cpp_snapshot.so:system/vendor/lib/libchromatix_imx132_cpp_snapshot.so \
    vendor/sony/amami/proprietary/vendor/lib/libchromatix_imx132_cpp_video.so:system/vendor/lib/libchromatix_imx132_cpp_video.so \
    vendor/sony/amami/proprietary/vendor/lib/libchromatix_imx132_default_video.so:system/vendor/lib/libchromatix_imx132_default_video.so \
    vendor/sony/amami/proprietary/vendor/lib/libchromatix_imx132_liveshot.so:system/vendor/lib/libchromatix_imx132_liveshot.so \
    vendor/sony/amami/proprietary/vendor/lib/libchromatix_imx132_postproc.so:system/vendor/lib/libchromatix_imx132_postproc.so \
    vendor/sony/amami/proprietary/vendor/lib/libchromatix_imx132_preview.so:system/vendor/lib/libchromatix_imx132_preview.so \
    vendor/sony/amami/proprietary/vendor/lib/libchromatix_imx132_snapshot.so:system/vendor/lib/libchromatix_imx132_snapshot.so \
    vendor/sony/amami/proprietary/vendor/lib/libchromatix_imx200_common.so:system/vendor/lib/libchromatix_imx200_common.so \
    vendor/sony/amami/proprietary/vendor/lib/libchromatix_imx200_cpp_hfr_120.so:system/vendor/lib/libchromatix_imx200_cpp_hfr_120.so \
    vendor/sony/amami/proprietary/vendor/lib/libchromatix_imx200_cpp_hfr_60.so:system/vendor/lib/libchromatix_imx200_cpp_hfr_60.so \
    vendor/sony/amami/proprietary/vendor/lib/libchromatix_imx200_cpp_hfr_90.so:system/vendor/lib/libchromatix_imx200_cpp_hfr_90.so \
    vendor/sony/amami/proprietary/vendor/lib/libchromatix_imx200_cpp_liveshot.so:system/vendor/lib/libchromatix_imx200_cpp_liveshot.so \
    vendor/sony/amami/proprietary/vendor/lib/libchromatix_imx200_cpp_preview.so:system/vendor/lib/libchromatix_imx200_cpp_preview.so \
    vendor/sony/amami/proprietary/vendor/lib/libchromatix_imx200_cpp_snapshot.so:system/vendor/lib/libchromatix_imx200_cpp_snapshot.so \
    vendor/sony/amami/proprietary/vendor/lib/libchromatix_imx200_cpp_snapshot_hdr.so:system/vendor/lib/libchromatix_imx200_cpp_snapshot_hdr.so \
    vendor/sony/amami/proprietary/vendor/lib/libchromatix_imx200_cpp_video.so:system/vendor/lib/libchromatix_imx200_cpp_video.so \
    vendor/sony/amami/proprietary/vendor/lib/libchromatix_imx200_cpp_video_4k.so:system/vendor/lib/libchromatix_imx200_cpp_video_4k.so \
    vendor/sony/amami/proprietary/vendor/lib/libchromatix_imx200_cpp_video_hdr.so:system/vendor/lib/libchromatix_imx200_cpp_video_hdr.so \
    vendor/sony/amami/proprietary/vendor/lib/libchromatix_imx200_default_video.so:system/vendor/lib/libchromatix_imx200_default_video.so \
    vendor/sony/amami/proprietary/vendor/lib/libchromatix_imx200_hfr_120.so:system/vendor/lib/libchromatix_imx200_hfr_120.so \
    vendor/sony/amami/proprietary/vendor/lib/libchromatix_imx200_hfr_60.so:system/vendor/lib/libchromatix_imx200_hfr_60.so \
    vendor/sony/amami/proprietary/vendor/lib/libchromatix_imx200_hfr_90.so:system/vendor/lib/libchromatix_imx200_hfr_90.so \
    vendor/sony/amami/proprietary/vendor/lib/libchromatix_imx200_liveshot.so:system/vendor/lib/libchromatix_imx200_liveshot.so \
    vendor/sony/amami/proprietary/vendor/lib/libchromatix_imx200_postproc.so:system/vendor/lib/libchromatix_imx200_postproc.so \
    vendor/sony/amami/proprietary/vendor/lib/libchromatix_imx200_preview.so:system/vendor/lib/libchromatix_imx200_preview.so \
    vendor/sony/amami/proprietary/vendor/lib/libchromatix_imx200_snapshot.so:system/vendor/lib/libchromatix_imx200_snapshot.so \
    vendor/sony/amami/proprietary/vendor/lib/libchromatix_imx200_snapshot_hdr.so:system/vendor/lib/libchromatix_imx200_snapshot_hdr.so \
    vendor/sony/amami/proprietary/vendor/lib/libchromatix_imx200_video_4k.so:system/vendor/lib/libchromatix_imx200_video_4k.so \
    vendor/sony/amami/proprietary/vendor/lib/libchromatix_imx200_video_hdr.so:system/vendor/lib/libchromatix_imx200_video_hdr.so \
    vendor/sony/amami/proprietary/vendor/lib/libmmcamera_imx132.so:system/vendor/lib/libmmcamera_imx132.so \
    vendor/sony/amami/proprietary/vendor/lib/libmmcamera_imx200.so:system/vendor/lib/libmmcamera_imx200.so
