# Copyright (C) 2011-2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/amami/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/sony/amami/proprietary/bin/chargemon:system/bin/chargemon \
    vendor/sony/amami/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
    vendor/sony/amami/proprietary/bin/updatemiscta:system/bin/updatemiscta \
    vendor/sony/amami/proprietary/etc/acdbdata/Liquid/Liquid_Handset_cal.acdb:system/etc/acdbdata/Liquid/Liquid_Handset_cal.acdb \
    vendor/sony/amami/proprietary/etc/acdbdata/Liquid/Liquid_Speaker_cal.acdb:system/etc/acdbdata/Liquid/Liquid_Speaker_cal.acdb \
    vendor/sony/amami/proprietary/etc/acdbdata/MTP/MTP_Handset_cal.acdb:system/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
    vendor/sony/amami/proprietary/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:system/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
    vendor/sony/amami/proprietary/etc/firmware/touch_module_id_0x45.img:system/etc/firmware/touch_module_id_0x45.img \
    vendor/sony/amami/proprietary/etc/firmware/touch_module_id_0x48.img:system/etc/firmware/touch_module_id_0x48.img \
    vendor/sony/amami/proprietary/etc/firmware/touch_module_id_0x4d.img:system/etc/firmware/touch_module_id_0x4d.img \
    vendor/sony/amami/proprietary/etc/firmware/touch_module_id_0x4e.img:system/etc/firmware/touch_module_id_0x4e.img \
    vendor/sony/amami/proprietary/etc/firmware/touch_module_id_0x53.img:system/etc/firmware/touch_module_id_0x53.img \
    vendor/sony/amami/proprietary/etc/firmware/touch_module_id_0x54.img:system/etc/firmware/touch_module_id_0x54.img \
    vendor/sony/amami/proprietary/etc/firmware/touch_module_id_0x5d.img:system/etc/firmware/touch_module_id_0x5d.img \
    vendor/sony/amami/proprietary/etc/flashled_calc_parameters.cfg:system/etc/flashled_calc_parameters.cfg \
    vendor/sony/amami/proprietary/etc/sensor_def_qcomdev.conf:system/etc/sensor_def_qcomdev.conf \
    vendor/sony/amami/proprietary/etc/sensors_calib.conf:system/etc/sensors_calib.conf \
    vendor/sony/amami/proprietary/lib/libcald_hal.so:system/lib/libcald_hal.so \
    vendor/sony/amami/proprietary/lib/libcameralight.so:system/lib/libcameralight.so \
    vendor/sony/amami/proprietary/usr/idc/clearpad.idc:system/usr/idc/clearpad.idc \
    vendor/sony/amami/proprietary/vendor/camera/LGI02BN1.dat:system/vendor/camera/LGI02BN1.dat \
    vendor/sony/amami/proprietary/vendor/camera/LGI02BN1_CACAO.dat:system/vendor/camera/LGI02BN1_CACAO.dat \
    vendor/sony/amami/proprietary/vendor/camera/LGI02BN1_IMX132.dat:system/vendor/camera/LGI02BN1_IMX132.dat \
    vendor/sony/amami/proprietary/vendor/camera/SEM02BN1.dat:system/vendor/camera/SEM02BN1.dat \
    vendor/sony/amami/proprietary/vendor/camera/SEM02BN1_CACAO.dat:system/vendor/camera/SEM02BN1_CACAO.dat \
    vendor/sony/amami/proprietary/vendor/camera/SEM02BN1_IMX132.dat:system/vendor/camera/SEM02BN1_IMX132.dat \
    vendor/sony/amami/proprietary/vendor/camera/SOI13BS9.dat:system/vendor/camera/SOI13BS9.dat \
    vendor/sony/amami/proprietary/vendor/camera/SOI13BS9_CACAO.dat:system/vendor/camera/SOI13BS9_CACAO.dat \
    vendor/sony/amami/proprietary/vendor/camera/SOI20BS0.dat:system/vendor/camera/SOI20BS0.dat \
    vendor/sony/amami/proprietary/vendor/camera/SOI20BS0_BU64296GWX.dat:system/vendor/camera/SOI20BS0_BU64296GWX.dat \
    vendor/sony/amami/proprietary/vendor/camera/SOI20BS0_CACAO.dat:system/vendor/camera/SOI20BS0_CACAO.dat \
    vendor/sony/amami/proprietary/vendor/camera/SOI20BS0_IMX200.dat:system/vendor/camera/SOI20BS0_IMX200.dat \
    vendor/sony/amami/proprietary/vendor/camera/flash.dat:system/vendor/camera/flash.dat \
    vendor/sony/amami/proprietary/vendor/camera/product.dat:system/vendor/camera/product.dat \
    vendor/sony/amami/proprietary/vendor/camera/product_CACAO.dat:system/vendor/camera/product_CACAO.dat \
    vendor/sony/amami/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/sony/amami/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/sony/amami/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/sony/amami/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/sony/amami/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/sony/amami/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/sony/amami/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/sony/amami/proprietary/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so
