# Copyright (C) 2013-2016 The CyanogenMod Project
# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/pollux_windy/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/sony/pollux_windy/proprietary/etc/firmware/apps.mbn:system/etc/firmware/apps.mbn \
    vendor/sony/pollux_windy/proprietary/etc/firmware/dsp3.mbn:system/etc/firmware/dsp3.mbn \
    vendor/sony/pollux_windy/proprietary/etc/firmware/dsps.b00:system/etc/firmware/dsps.b00 \
    vendor/sony/pollux_windy/proprietary/etc/firmware/dsps.b01:system/etc/firmware/dsps.b01 \
    vendor/sony/pollux_windy/proprietary/etc/firmware/dsps.b02:system/etc/firmware/dsps.b02 \
    vendor/sony/pollux_windy/proprietary/etc/firmware/dsps.b03:system/etc/firmware/dsps.b03 \
    vendor/sony/pollux_windy/proprietary/etc/firmware/dsps.b04:system/etc/firmware/dsps.b04 \
    vendor/sony/pollux_windy/proprietary/etc/firmware/dsps.b05:system/etc/firmware/dsps.b05 \
    vendor/sony/pollux_windy/proprietary/etc/firmware/dsps.mdt:system/etc/firmware/dsps.mdt \
    vendor/sony/pollux_windy/proprietary/etc/firmware/gss.b00:system/etc/firmware/gss.b00 \
    vendor/sony/pollux_windy/proprietary/etc/firmware/gss.b01:system/etc/firmware/gss.b01 \
    vendor/sony/pollux_windy/proprietary/etc/firmware/gss.b02:system/etc/firmware/gss.b02 \
    vendor/sony/pollux_windy/proprietary/etc/firmware/gss.b03:system/etc/firmware/gss.b03 \
    vendor/sony/pollux_windy/proprietary/etc/firmware/gss.b04:system/etc/firmware/gss.b04 \
    vendor/sony/pollux_windy/proprietary/etc/firmware/gss.b05:system/etc/firmware/gss.b05 \
    vendor/sony/pollux_windy/proprietary/etc/firmware/gss.b06:system/etc/firmware/gss.b06 \
    vendor/sony/pollux_windy/proprietary/etc/firmware/gss.b07:system/etc/firmware/gss.b07 \
    vendor/sony/pollux_windy/proprietary/etc/firmware/gss.b08:system/etc/firmware/gss.b08 \
    vendor/sony/pollux_windy/proprietary/etc/firmware/gss.b09:system/etc/firmware/gss.b09 \
    vendor/sony/pollux_windy/proprietary/etc/firmware/gss.b10:system/etc/firmware/gss.b10 \
    vendor/sony/pollux_windy/proprietary/etc/firmware/gss.b11:system/etc/firmware/gss.b11 \
    vendor/sony/pollux_windy/proprietary/etc/firmware/gss.mdt:system/etc/firmware/gss.mdt \
    vendor/sony/pollux_windy/proprietary/lib/hw/nfc.msm8960.so:system/lib/hw/nfc.msm8960.so

PRODUCT_COPY_FILES += \
    vendor/sony/pollux_windy/proprietary/bin/irsc_util:system/bin/irsc_util \
    vendor/sony/pollux_windy/proprietary/bin/rmt_storage:system/bin/rmt_storage
