# Copyright (C) 2011-2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/sirius/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/sony/sirius/proprietary/bin/chargemon:system/bin/chargemon \
    vendor/sony/sirius/proprietary/bin/illumination_service:system/bin/illumination_service \
    vendor/sony/sirius/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
    vendor/sony/sirius/proprietary/bin/updatemiscta:system/bin/updatemiscta \
    vendor/sony/sirius/proprietary/etc/acdbdata/Liquid/Liquid_Handset_cal.acdb:system/etc/acdbdata/Liquid/Liquid_Handset_cal.acdb \
    vendor/sony/sirius/proprietary/etc/acdbdata/Liquid/Liquid_Speaker_cal.acdb:system/etc/acdbdata/Liquid/Liquid_Speaker_cal.acdb \
    vendor/sony/sirius/proprietary/etc/acdbdata/MTP/MTP_Handset_cal.acdb:system/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
    vendor/sony/sirius/proprietary/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:system/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x75_config_id_0x0108.bin:system/etc/firmware/touch_chip_id_0x75_config_id_0x0108.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x75_config_id_0x0109.bin:system/etc/firmware/touch_chip_id_0x75_config_id_0x0109.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x75_config_id_0x010a.bin:system/etc/firmware/touch_chip_id_0x75_config_id_0x010a.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x75_config_id_0x0118.bin:system/etc/firmware/touch_chip_id_0x75_config_id_0x0118.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x75_config_id_0x0119.bin:system/etc/firmware/touch_chip_id_0x75_config_id_0x0119.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x75_config_id_0x011a.bin:system/etc/firmware/touch_chip_id_0x75_config_id_0x011a.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x75_config_id_0x0141.bin:system/etc/firmware/touch_chip_id_0x75_config_id_0x0141.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x75_config_id_0x0142.bin:system/etc/firmware/touch_chip_id_0x75_config_id_0x0142.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x75_config_id_0x0151.bin:system/etc/firmware/touch_chip_id_0x75_config_id_0x0151.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x75_config_id_0x0152.bin:system/etc/firmware/touch_chip_id_0x75_config_id_0x0152.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x75_config_id_0x0181.bin:system/etc/firmware/touch_chip_id_0x75_config_id_0x0181.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x75_config_id_0x0191.bin:system/etc/firmware/touch_chip_id_0x75_config_id_0x0191.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x75_config_id_0x0241.bin:system/etc/firmware/touch_chip_id_0x75_config_id_0x0241.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x75_config_id_0x0251.bin:system/etc/firmware/touch_chip_id_0x75_config_id_0x0251.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x75_config_id_0x0281.bin:system/etc/firmware/touch_chip_id_0x75_config_id_0x0281.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x75_config_id_0x0291.bin:system/etc/firmware/touch_chip_id_0x75_config_id_0x0291.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x75_config_id_0x0395.bin:system/etc/firmware/touch_chip_id_0x75_config_id_0x0395.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x0108.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x0108.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x0109.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x0109.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x010c.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x010c.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x010e.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x010e.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x0118.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x0118.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x0119.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x0119.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x0141.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x0141.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x0146.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x0146.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x0148.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x0148.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x0149.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x0149.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x0151.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x0151.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x0154.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x0154.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x0156.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x0156.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x0158.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x0158.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x0159.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x0159.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x015c.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x015c.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x0181.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x0181.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x0184.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x0184.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x0188.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x0188.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x0189.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x0189.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x018b.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x018b.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x018c.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x018c.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x018d.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x018d.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x0191.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x0191.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x0198.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x0198.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x0199.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x0199.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x0241.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x0241.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x0246.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x0246.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x0247.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x0247.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x0251.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x0251.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x0254.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x0254.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x0256.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x0256.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x0257.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x0257.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x0399.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x0399.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x039D.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x039D.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x0409.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x0409.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x0459.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x0459.bin \
    vendor/sony/sirius/proprietary/etc/firmware/touch_chip_id_0x78_config_id_0x0489.bin:system/etc/firmware/touch_chip_id_0x78_config_id_0x0489.bin \
    vendor/sony/sirius/proprietary/etc/flashled_calc_parameters.cfg:system/etc/flashled_calc_parameters.cfg \
    vendor/sony/sirius/proprietary/etc/mixer_paths.xml:system/etc/mixer_paths.xml \
    vendor/sony/sirius/proprietary/etc/sensor_def_qcomdev.conf:system/etc/sensor_def_qcomdev.conf \
    vendor/sony/sirius/proprietary/etc/sensors_calib.conf:system/etc/sensors_calib.conf \
    vendor/sony/sirius/proprietary/etc/sysmon.cfg:system/etc/sysmon.cfg \
    vendor/sony/sirius/proprietary/lib/libcald_hal.so:system/lib/libcald_hal.so \
    vendor/sony/sirius/proprietary/lib/libcameralight.so:system/lib/libcameralight.so \
    vendor/sony/sirius/proprietary/lib/libsysmon_jni.so:system/lib/libsysmon_jni.so \
    vendor/sony/sirius/proprietary/usr/idc/max1187x_touchscreen_0.idc:system/usr/idc/max1187x_touchscreen_0.idc \
    vendor/sony/sirius/proprietary/vendor/camera/LGI02BN1.dat:system/vendor/camera/LGI02BN1.dat \
    vendor/sony/sirius/proprietary/vendor/camera/LGI02BN1_CACAO.dat:system/vendor/camera/LGI02BN1_CACAO.dat \
    vendor/sony/sirius/proprietary/vendor/camera/LGI02BN1_IMX132.dat:system/vendor/camera/LGI02BN1_IMX132.dat \
    vendor/sony/sirius/proprietary/vendor/camera/SEM02BN1.dat:system/vendor/camera/SEM02BN1.dat \
    vendor/sony/sirius/proprietary/vendor/camera/SEM02BN1_CACAO.dat:system/vendor/camera/SEM02BN1_CACAO.dat \
    vendor/sony/sirius/proprietary/vendor/camera/SEM02BN1_IMX132.dat:system/vendor/camera/SEM02BN1_IMX132.dat \
    vendor/sony/sirius/proprietary/vendor/camera/SOI20BS0.dat:system/vendor/camera/SOI20BS0.dat \
    vendor/sony/sirius/proprietary/vendor/camera/SOI20BS0_BU64296GWX.dat:system/vendor/camera/SOI20BS0_BU64296GWX.dat \
    vendor/sony/sirius/proprietary/vendor/camera/SOI20BS0_CACAO.dat:system/vendor/camera/SOI20BS0_CACAO.dat \
    vendor/sony/sirius/proprietary/vendor/camera/SOI20BS0_IMX200.dat:system/vendor/camera/SOI20BS0_IMX200.dat \
    vendor/sony/sirius/proprietary/vendor/camera/flash.dat:system/vendor/camera/flash.dat \
    vendor/sony/sirius/proprietary/vendor/camera/product.dat:system/vendor/camera/product.dat \
    vendor/sony/sirius/proprietary/vendor/camera/product_CACAO.dat:system/vendor/camera/product_CACAO.dat \
    vendor/sony/sirius/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/sony/sirius/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/sony/sirius/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/sony/sirius/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/sony/sirius/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/sony/sirius/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/sony/sirius/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/sony/sirius/proprietary/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so
