# Copyright (C) 2011-2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/z3dual/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/sony/z3dual/proprietary/etc/firmware/adsp.b00:system/etc/firmware/adsp.b00 \
    vendor/sony/z3dual/proprietary/etc/firmware/adsp.b01:system/etc/firmware/adsp.b01 \
    vendor/sony/z3dual/proprietary/etc/firmware/adsp.b02:system/etc/firmware/adsp.b02 \
    vendor/sony/z3dual/proprietary/etc/firmware/adsp.b03:system/etc/firmware/adsp.b03 \
    vendor/sony/z3dual/proprietary/etc/firmware/adsp.b04:system/etc/firmware/adsp.b04 \
    vendor/sony/z3dual/proprietary/etc/firmware/adsp.b05:system/etc/firmware/adsp.b05 \
    vendor/sony/z3dual/proprietary/etc/firmware/adsp.b06:system/etc/firmware/adsp.b06 \
    vendor/sony/z3dual/proprietary/etc/firmware/adsp.b07:system/etc/firmware/adsp.b07 \
    vendor/sony/z3dual/proprietary/etc/firmware/adsp.b08:system/etc/firmware/adsp.b08 \
    vendor/sony/z3dual/proprietary/etc/firmware/adsp.b09:system/etc/firmware/adsp.b09 \
    vendor/sony/z3dual/proprietary/etc/firmware/adsp.b10:system/etc/firmware/adsp.b10 \
    vendor/sony/z3dual/proprietary/etc/firmware/adsp.b11:system/etc/firmware/adsp.b11 \
    vendor/sony/z3dual/proprietary/etc/firmware/adsp.b12:system/etc/firmware/adsp.b12 \
    vendor/sony/z3dual/proprietary/etc/firmware/adsp.mdt:system/etc/firmware/adsp.mdt \
    vendor/sony/z3dual/proprietary/etc/firmware/mba.b00:system/etc/firmware/mba.b00 \
    vendor/sony/z3dual/proprietary/etc/firmware/mba.mdt:system/etc/firmware/mba.mdt \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b00:system/etc/firmware/modem.b00 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b01:system/etc/firmware/modem.b01 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b02:system/etc/firmware/modem.b02 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b03:system/etc/firmware/modem.b03 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b06:system/etc/firmware/modem.b06 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b08:system/etc/firmware/modem.b08 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b09:system/etc/firmware/modem.b09 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b11:system/etc/firmware/modem.b11 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b12:system/etc/firmware/modem.b12 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b13:system/etc/firmware/modem.b13 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b14:system/etc/firmware/modem.b14 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b15:system/etc/firmware/modem.b15 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b16:system/etc/firmware/modem.b16 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b17:system/etc/firmware/modem.b17 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b18:system/etc/firmware/modem.b18 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b19:system/etc/firmware/modem.b19 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b22:system/etc/firmware/modem.b22 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b23:system/etc/firmware/modem.b23 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b24:system/etc/firmware/modem.b24 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b25:system/etc/firmware/modem.b25 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.mdt:system/etc/firmware/modem.mdt \
    vendor/sony/z3dual/proprietary/etc/firmware/tzfullseg.b00:system/etc/firmware/tzfullseg.b00 \
    vendor/sony/z3dual/proprietary/etc/firmware/tzfullseg.b01:system/etc/firmware/tzfullseg.b01 \
    vendor/sony/z3dual/proprietary/etc/firmware/tzfullseg.b02:system/etc/firmware/tzfullseg.b02 \
    vendor/sony/z3dual/proprietary/etc/firmware/tzfullseg.b03:system/etc/firmware/tzfullseg.b03 \
    vendor/sony/z3dual/proprietary/etc/firmware/tzfullseg.mdt:system/etc/firmware/tzfullseg.mdt \
    vendor/sony/z3dual/proprietary/etc/firmware/tzplayrdy.b00:system/etc/firmware/tzplayrdy.b00 \
    vendor/sony/z3dual/proprietary/etc/firmware/tzplayrdy.b01:system/etc/firmware/tzplayrdy.b01 \
    vendor/sony/z3dual/proprietary/etc/firmware/tzplayrdy.b02:system/etc/firmware/tzplayrdy.b02 \
    vendor/sony/z3dual/proprietary/etc/firmware/tzplayrdy.b03:system/etc/firmware/tzplayrdy.b03 \
    vendor/sony/z3dual/proprietary/etc/firmware/tzplayrdy.mdt:system/etc/firmware/tzplayrdy.mdt
