# Copyright (C) 2011-2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/z3dual/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/sony/z3dual/proprietary/bin/cnd:system/bin/cnd \
    vendor/sony/z3dual/proprietary/bin/efsks:system/bin/efsks \
    vendor/sony/z3dual/proprietary/bin/irsc_util:system/bin/irsc_util \
    vendor/sony/z3dual/proprietary/bin/ks:system/bin/ks \
    vendor/sony/z3dual/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/sony/z3dual/proprietary/bin/qcks:system/bin/qcks \
    vendor/sony/z3dual/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/sony/z3dual/proprietary/bin/rfs_access:system/bin/rfs_access \
    vendor/sony/z3dual/proprietary/bin/rild:system/bin/rild \
    vendor/sony/z3dual/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
    vendor/sony/z3dual/proprietary/bin/suntrold:system/bin/suntrold \
    vendor/sony/z3dual/proprietary/etc/cne/SwimConfig.xml:system/etc/cne/SwimConfig.xml \
    vendor/sony/z3dual/proprietary/etc/cne/andsfCne.xml:system/etc/cne/andsfCne.xml \
    vendor/sony/z3dual/proprietary/etc/data/qmi_config.xml:system/etc/data/qmi_config.xml \
    vendor/sony/z3dual/proprietary/etc/firmware/adsp.b00:system/etc/firmware/adsp.b00 \
    vendor/sony/z3dual/proprietary/etc/firmware/adsp.b01:system/etc/firmware/adsp.b01 \
    vendor/sony/z3dual/proprietary/etc/firmware/adsp.b02:system/etc/firmware/adsp.b02 \
    vendor/sony/z3dual/proprietary/etc/firmware/adsp.b03:system/etc/firmware/adsp.b03 \
    vendor/sony/z3dual/proprietary/etc/firmware/adsp.b04:system/etc/firmware/adsp.b04 \
    vendor/sony/z3dual/proprietary/etc/firmware/adsp.b05:system/etc/firmware/adsp.b05 \
    vendor/sony/z3dual/proprietary/etc/firmware/adsp.b06:system/etc/firmware/adsp.b06 \
    vendor/sony/z3dual/proprietary/etc/firmware/adsp.b07:system/etc/firmware/adsp.b07 \
    vendor/sony/z3dual/proprietary/etc/firmware/adsp.b08:system/etc/firmware/adsp.b08 \
    vendor/sony/z3dual/proprietary/etc/firmware/adsp.b09:system/etc/firmware/adsp.b09 \
    vendor/sony/z3dual/proprietary/etc/firmware/adsp.b10:system/etc/firmware/adsp.b10 \
    vendor/sony/z3dual/proprietary/etc/firmware/adsp.b11:system/etc/firmware/adsp.b11 \
    vendor/sony/z3dual/proprietary/etc/firmware/adsp.b12:system/etc/firmware/adsp.b12 \
    vendor/sony/z3dual/proprietary/etc/firmware/adsp.mdt:system/etc/firmware/adsp.mdt \
    vendor/sony/z3dual/proprietary/etc/firmware/mba.b00:system/etc/firmware/mba.b00 \
    vendor/sony/z3dual/proprietary/etc/firmware/mba.mdt:system/etc/firmware/mba.mdt \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b00:system/etc/firmware/modem.b00 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b01:system/etc/firmware/modem.b01 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b02:system/etc/firmware/modem.b02 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b03:system/etc/firmware/modem.b03 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b06:system/etc/firmware/modem.b06 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b08:system/etc/firmware/modem.b08 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b09:system/etc/firmware/modem.b09 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b11:system/etc/firmware/modem.b11 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b12:system/etc/firmware/modem.b12 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b13:system/etc/firmware/modem.b13 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b14:system/etc/firmware/modem.b14 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b15:system/etc/firmware/modem.b15 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b16:system/etc/firmware/modem.b16 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b17:system/etc/firmware/modem.b17 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b18:system/etc/firmware/modem.b18 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b19:system/etc/firmware/modem.b19 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b22:system/etc/firmware/modem.b22 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b23:system/etc/firmware/modem.b23 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b24:system/etc/firmware/modem.b24 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.b25:system/etc/firmware/modem.b25 \
    vendor/sony/z3dual/proprietary/etc/firmware/modem.mdt:system/etc/firmware/modem.mdt \
    vendor/sony/z3dual/proprietary/etc/firmware/tzfullseg.b00:system/etc/firmware/tzfullseg.b00 \
    vendor/sony/z3dual/proprietary/etc/firmware/tzfullseg.b01:system/etc/firmware/tzfullseg.b01 \
    vendor/sony/z3dual/proprietary/etc/firmware/tzfullseg.b02:system/etc/firmware/tzfullseg.b02 \
    vendor/sony/z3dual/proprietary/etc/firmware/tzfullseg.b03:system/etc/firmware/tzfullseg.b03 \
    vendor/sony/z3dual/proprietary/etc/firmware/tzfullseg.mdt:system/etc/firmware/tzfullseg.mdt \
    vendor/sony/z3dual/proprietary/etc/firmware/tzplayrdy.b00:system/etc/firmware/tzplayrdy.b00 \
    vendor/sony/z3dual/proprietary/etc/firmware/tzplayrdy.b01:system/etc/firmware/tzplayrdy.b01 \
    vendor/sony/z3dual/proprietary/etc/firmware/tzplayrdy.b02:system/etc/firmware/tzplayrdy.b02 \
    vendor/sony/z3dual/proprietary/etc/firmware/tzplayrdy.b03:system/etc/firmware/tzplayrdy.b03 \
    vendor/sony/z3dual/proprietary/etc/firmware/tzplayrdy.mdt:system/etc/firmware/tzplayrdy.mdt \
    vendor/sony/z3dual/proprietary/etc/firmware/wlan/bcmdhd/bcmdhd.cal:system/etc/firmware/wlan/bcmdhd/bcmdhd.cal \
    vendor/sony/z3dual/proprietary/etc/permissions/com.sonyericsson.android.semcrilextension.xml:system/etc/permissions/com.sonyericsson.android.semcrilextension.xml \
    vendor/sony/z3dual/proprietary/etc/permissions/qcnvitems.xml:system/etc/permissions/qcnvitems.xml \
    vendor/sony/z3dual/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    vendor/sony/z3dual/proprietary/etc/sensor_def_qcomdev.conf:system/etc/sensor_def_qcomdev.conf \
    vendor/sony/z3dual/proprietary/lib/libkeyctrl.so:system/lib/libkeyctrl.so \
    vendor/sony/z3dual/proprietary/lib/libmdmdetect.so:system/lib/libmdmdetect.so \
    vendor/sony/z3dual/proprietary/lib/libpin-cache.so:system/lib/libpin-cache.so \
    vendor/sony/z3dual/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/sony/z3dual/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/sony/z3dual/proprietary/lib/librilutils.so:system/lib/librilutils.so \
    vendor/sony/z3dual/proprietary/lib/libstartup-reason.so:system/lib/libstartup-reason.so \
    vendor/sony/z3dual/proprietary/vendor/lib/hw/sensors.msm8974.so:system/vendor/lib/hw/sensors.msm8974.so \
    vendor/sony/z3dual/proprietary/vendor/lib/libcne.so:system/vendor/lib/libcne.so \
    vendor/sony/z3dual/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
    vendor/sony/z3dual/proprietary/vendor/lib/libcneconn.so:system/vendor/lib/libcneconn.so \
    vendor/sony/z3dual/proprietary/vendor/lib/libcneqmiutils.so:system/vendor/lib/libcneqmiutils.so \
    vendor/sony/z3dual/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/sony/z3dual/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/sony/z3dual/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/sony/z3dual/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/sony/z3dual/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/sony/z3dual/proprietary/vendor/lib/libmasc.so:system/vendor/lib/libmasc.so \
    vendor/sony/z3dual/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/sony/z3dual/proprietary/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so \
    vendor/sony/z3dual/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/sony/z3dual/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/sony/z3dual/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/sony/z3dual/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/sony/z3dual/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/sony/z3dual/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/sony/z3dual/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/sony/z3dual/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/sony/z3dual/proprietary/vendor/lib/libqmi_csvt_srvc.so:system/vendor/lib/libqmi_csvt_srvc.so \
    vendor/sony/z3dual/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/sony/z3dual/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/sony/z3dual/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    vendor/sony/z3dual/proprietary/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so \
    vendor/sony/z3dual/proprietary/vendor/lib/libsensor_reg.so:system/vendor/lib/libsensor_reg.so \
    vendor/sony/z3dual/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
    vendor/sony/z3dual/proprietary/vendor/lib/libsystem_health_mon.so:system/vendor/lib/libsystem_health_mon.so \
    vendor/sony/z3dual/proprietary/vendor/lib/libvendorconn.so:system/vendor/lib/libvendorconn.so \
    vendor/sony/z3dual/proprietary/vendor/lib/libwqe.so:system/vendor/lib/libwqe.so \
    vendor/sony/z3dual/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so
