# Copyright (C) 2014-2016 The CyanogenMod Project
# Copyright (C) 2017-2020 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/castor_windy/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/sony/castor_windy

PRODUCT_COPY_FILES += \
    vendor/sony/castor_windy/proprietary/etc/acdbdata/Fluid/Fluid_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Fluid/Fluid_Bluetooth_cal.acdb \
    vendor/sony/castor_windy/proprietary/etc/acdbdata/Fluid/Fluid_General_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Fluid/Fluid_General_cal.acdb \
    vendor/sony/castor_windy/proprietary/etc/acdbdata/Fluid/Fluid_Global_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Fluid/Fluid_Global_cal.acdb \
    vendor/sony/castor_windy/proprietary/etc/acdbdata/Fluid/Fluid_Handset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Fluid/Fluid_Handset_cal.acdb \
    vendor/sony/castor_windy/proprietary/etc/acdbdata/Fluid/Fluid_Hdmi_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Fluid/Fluid_Hdmi_cal.acdb \
    vendor/sony/castor_windy/proprietary/etc/acdbdata/Fluid/Fluid_Headset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Fluid/Fluid_Headset_cal.acdb \
    vendor/sony/castor_windy/proprietary/etc/acdbdata/Fluid/Fluid_Speaker_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Fluid/Fluid_Speaker_cal.acdb \
    vendor/sony/castor_windy/proprietary/etc/acdbdata/Liquid/Liquid_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Liquid/Liquid_Bluetooth_cal.acdb \
    vendor/sony/castor_windy/proprietary/etc/acdbdata/Liquid/Liquid_General_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Liquid/Liquid_General_cal.acdb \
    vendor/sony/castor_windy/proprietary/etc/acdbdata/Liquid/Liquid_Global_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Liquid/Liquid_Global_cal.acdb \
    vendor/sony/castor_windy/proprietary/etc/acdbdata/Liquid/Liquid_Handset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Liquid/Liquid_Handset_cal.acdb \
    vendor/sony/castor_windy/proprietary/etc/acdbdata/Liquid/Liquid_Hdmi_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Liquid/Liquid_Hdmi_cal.acdb \
    vendor/sony/castor_windy/proprietary/etc/acdbdata/Liquid/Liquid_Headset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Liquid/Liquid_Headset_cal.acdb \
    vendor/sony/castor_windy/proprietary/etc/acdbdata/Liquid/Liquid_Speaker_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Liquid/Liquid_Speaker_cal.acdb \
    vendor/sony/castor_windy/proprietary/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb \
    vendor/sony/castor_windy/proprietary/etc/acdbdata/MTP/MTP_General_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_General_cal.acdb \
    vendor/sony/castor_windy/proprietary/etc/acdbdata/MTP/MTP_Global_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_Global_cal.acdb \
    vendor/sony/castor_windy/proprietary/etc/acdbdata/MTP/MTP_Handset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
    vendor/sony/castor_windy/proprietary/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb \
    vendor/sony/castor_windy/proprietary/etc/acdbdata/MTP/MTP_Headset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_Headset_cal.acdb \
    vendor/sony/castor_windy/proprietary/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
    vendor/sony/castor_windy/proprietary/etc/acdbdata/Sony/Sony_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Sony/Sony_Bluetooth_cal.acdb \
    vendor/sony/castor_windy/proprietary/etc/acdbdata/Sony/Sony_General_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Sony/Sony_General_cal.acdb \
    vendor/sony/castor_windy/proprietary/etc/acdbdata/Sony/Sony_Global_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Sony/Sony_Global_cal.acdb \
    vendor/sony/castor_windy/proprietary/etc/acdbdata/Sony/Sony_Handset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Sony/Sony_Handset_cal.acdb \
    vendor/sony/castor_windy/proprietary/etc/acdbdata/Sony/Sony_Hdmi_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Sony/Sony_Hdmi_cal.acdb \
    vendor/sony/castor_windy/proprietary/etc/acdbdata/Sony/Sony_Headset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Sony/Sony_Headset_cal.acdb \
    vendor/sony/castor_windy/proprietary/etc/acdbdata/Sony/Sony_Speaker_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Sony/Sony_Speaker_cal.acdb \
    vendor/sony/castor_windy/proprietary/vendor/firmware/BCM43xx.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/BCM43xx.hcd \
    vendor/sony/castor_windy/proprietary/vendor/firmware/adsp.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b00 \
    vendor/sony/castor_windy/proprietary/vendor/firmware/adsp.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b01 \
    vendor/sony/castor_windy/proprietary/vendor/firmware/adsp.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b02 \
    vendor/sony/castor_windy/proprietary/vendor/firmware/adsp.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b03 \
    vendor/sony/castor_windy/proprietary/vendor/firmware/adsp.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b04 \
    vendor/sony/castor_windy/proprietary/vendor/firmware/adsp.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b05 \
    vendor/sony/castor_windy/proprietary/vendor/firmware/adsp.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b06 \
    vendor/sony/castor_windy/proprietary/vendor/firmware/adsp.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b07 \
    vendor/sony/castor_windy/proprietary/vendor/firmware/adsp.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b08 \
    vendor/sony/castor_windy/proprietary/vendor/firmware/adsp.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b09 \
    vendor/sony/castor_windy/proprietary/vendor/firmware/adsp.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b10 \
    vendor/sony/castor_windy/proprietary/vendor/firmware/adsp.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b11 \
    vendor/sony/castor_windy/proprietary/vendor/firmware/adsp.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b12 \
    vendor/sony/castor_windy/proprietary/vendor/firmware/adsp.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.mdt \
    vendor/sony/castor_windy/proprietary/vendor/firmware/mba.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/mba.b00 \
    vendor/sony/castor_windy/proprietary/vendor/firmware/mba.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/mba.mdt \
    vendor/sony/castor_windy/proprietary/vendor/firmware/modem.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b00 \
    vendor/sony/castor_windy/proprietary/vendor/firmware/modem.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b01 \
    vendor/sony/castor_windy/proprietary/vendor/firmware/modem.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b02 \
    vendor/sony/castor_windy/proprietary/vendor/firmware/modem.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b03 \
    vendor/sony/castor_windy/proprietary/vendor/firmware/modem.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b05 \
    vendor/sony/castor_windy/proprietary/vendor/firmware/modem.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b08 \
    vendor/sony/castor_windy/proprietary/vendor/firmware/modem.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b10 \
    vendor/sony/castor_windy/proprietary/vendor/firmware/modem.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b11 \
    vendor/sony/castor_windy/proprietary/vendor/firmware/modem.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b13 \
    vendor/sony/castor_windy/proprietary/vendor/firmware/modem.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b14 \
    vendor/sony/castor_windy/proprietary/vendor/firmware/modem.b15:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b15 \
    vendor/sony/castor_windy/proprietary/vendor/firmware/modem.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b16 \
    vendor/sony/castor_windy/proprietary/vendor/firmware/modem.b17:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b17 \
    vendor/sony/castor_windy/proprietary/vendor/firmware/modem.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b18 \
    vendor/sony/castor_windy/proprietary/vendor/firmware/modem.b19:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b19 \
    vendor/sony/castor_windy/proprietary/vendor/firmware/modem.b20:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b20 \
    vendor/sony/castor_windy/proprietary/vendor/firmware/modem.b21:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b21 \
    vendor/sony/castor_windy/proprietary/vendor/firmware/modem.b22:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b22 \
    vendor/sony/castor_windy/proprietary/vendor/firmware/modem.b25:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b25 \
    vendor/sony/castor_windy/proprietary/vendor/firmware/modem.b26:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b26 \
    vendor/sony/castor_windy/proprietary/vendor/firmware/modem.b27:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b27 \
    vendor/sony/castor_windy/proprietary/vendor/firmware/modem.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.mdt \
    vendor/sony/castor_windy/proprietary/vendor/firmware/touch_module_id_0x60.img:$(TARGET_COPY_OUT_VENDOR)/firmware/touch_module_id_0x60.img \
    vendor/sony/castor_windy/proprietary/vendor/firmware/touch_module_id_0x61.img:$(TARGET_COPY_OUT_VENDOR)/firmware/touch_module_id_0x61.img \
    vendor/sony/castor_windy/proprietary/vendor/etc/tfa98xx/FMSpeaker_btm.eq:$(TARGET_COPY_OUT_VENDOR)/etc/tfa98xx/FMSpeaker_btm.eq \
    vendor/sony/castor_windy/proprietary/vendor/etc/tfa98xx/FMSpeaker_btm.preset:$(TARGET_COPY_OUT_VENDOR)/etc/tfa98xx/FMSpeaker_btm.preset \
    vendor/sony/castor_windy/proprietary/vendor/etc/tfa98xx/FMSpeaker_top.eq:$(TARGET_COPY_OUT_VENDOR)/etc/tfa98xx/FMSpeaker_top.eq \
    vendor/sony/castor_windy/proprietary/vendor/etc/tfa98xx/FMSpeaker_top.preset:$(TARGET_COPY_OUT_VENDOR)/etc/tfa98xx/FMSpeaker_top.preset \
    vendor/sony/castor_windy/proprietary/vendor/etc/tfa98xx/HiFiSpeakerRing_btm.eq:$(TARGET_COPY_OUT_VENDOR)/etc/tfa98xx/HiFiSpeakerRing_btm.eq \
    vendor/sony/castor_windy/proprietary/vendor/etc/tfa98xx/HiFiSpeakerRing_btm.preset:$(TARGET_COPY_OUT_VENDOR)/etc/tfa98xx/HiFiSpeakerRing_btm.preset \
    vendor/sony/castor_windy/proprietary/vendor/etc/tfa98xx/HiFiSpeakerRing_top.eq:$(TARGET_COPY_OUT_VENDOR)/etc/tfa98xx/HiFiSpeakerRing_top.eq \
    vendor/sony/castor_windy/proprietary/vendor/etc/tfa98xx/HiFiSpeakerRing_top.preset:$(TARGET_COPY_OUT_VENDOR)/etc/tfa98xx/HiFiSpeakerRing_top.preset \
    vendor/sony/castor_windy/proprietary/vendor/etc/tfa98xx/HiFiSpeakerSforce_btm.eq:$(TARGET_COPY_OUT_VENDOR)/etc/tfa98xx/HiFiSpeakerSforce_btm.eq \
    vendor/sony/castor_windy/proprietary/vendor/etc/tfa98xx/HiFiSpeakerSforce_btm.preset:$(TARGET_COPY_OUT_VENDOR)/etc/tfa98xx/HiFiSpeakerSforce_btm.preset \
    vendor/sony/castor_windy/proprietary/vendor/etc/tfa98xx/HiFiSpeakerSforce_top.eq:$(TARGET_COPY_OUT_VENDOR)/etc/tfa98xx/HiFiSpeakerSforce_top.eq \
    vendor/sony/castor_windy/proprietary/vendor/etc/tfa98xx/HiFiSpeakerSforce_top.preset:$(TARGET_COPY_OUT_VENDOR)/etc/tfa98xx/HiFiSpeakerSforce_top.preset \
    vendor/sony/castor_windy/proprietary/vendor/etc/tfa98xx/HiFiSpeaker_btm.eq:$(TARGET_COPY_OUT_VENDOR)/etc/tfa98xx/HiFiSpeaker_btm.eq \
    vendor/sony/castor_windy/proprietary/vendor/etc/tfa98xx/HiFiSpeaker_btm.preset:$(TARGET_COPY_OUT_VENDOR)/etc/tfa98xx/HiFiSpeaker_btm.preset \
    vendor/sony/castor_windy/proprietary/vendor/etc/tfa98xx/HiFiSpeaker_top.eq:$(TARGET_COPY_OUT_VENDOR)/etc/tfa98xx/HiFiSpeaker_top.eq \
    vendor/sony/castor_windy/proprietary/vendor/etc/tfa98xx/HiFiSpeaker_top.preset:$(TARGET_COPY_OUT_VENDOR)/etc/tfa98xx/HiFiSpeaker_top.preset \
    vendor/sony/castor_windy/proprietary/vendor/etc/tfa98xx/TFA9890.patch:$(TARGET_COPY_OUT_VENDOR)/etc/tfa98xx/TFA9890.patch \
    vendor/sony/castor_windy/proprietary/vendor/etc/tfa98xx/TFA9890_Receiver.config:$(TARGET_COPY_OUT_VENDOR)/etc/tfa98xx/TFA9890_Receiver.config \
    vendor/sony/castor_windy/proprietary/vendor/etc/tfa98xx/TFA9890_btm.config:$(TARGET_COPY_OUT_VENDOR)/etc/tfa98xx/TFA9890_btm.config \
    vendor/sony/castor_windy/proprietary/vendor/etc/tfa98xx/TFA9890_top.config:$(TARGET_COPY_OUT_VENDOR)/etc/tfa98xx/TFA9890_top.config \
    vendor/sony/castor_windy/proprietary/vendor/etc/tfa98xx/VoiceCallEarpice_top.eq:$(TARGET_COPY_OUT_VENDOR)/etc/tfa98xx/VoiceCallEarpice_top.eq \
    vendor/sony/castor_windy/proprietary/vendor/etc/tfa98xx/VoiceCallEarpice_top.preset:$(TARGET_COPY_OUT_VENDOR)/etc/tfa98xx/VoiceCallEarpice_top.preset \
    vendor/sony/castor_windy/proprietary/vendor/etc/tfa98xx/VoiceCallSpeaker_btm.eq:$(TARGET_COPY_OUT_VENDOR)/etc/tfa98xx/VoiceCallSpeaker_btm.eq \
    vendor/sony/castor_windy/proprietary/vendor/etc/tfa98xx/VoiceCallSpeaker_btm.preset:$(TARGET_COPY_OUT_VENDOR)/etc/tfa98xx/VoiceCallSpeaker_btm.preset \
    vendor/sony/castor_windy/proprietary/vendor/etc/tfa98xx/VoiceCallSpeaker_top.eq:$(TARGET_COPY_OUT_VENDOR)/etc/tfa98xx/VoiceCallSpeaker_top.eq \
    vendor/sony/castor_windy/proprietary/vendor/etc/tfa98xx/VoiceCallSpeaker_top.preset:$(TARGET_COPY_OUT_VENDOR)/etc/tfa98xx/VoiceCallSpeaker_top.preset \
    vendor/sony/castor_windy/proprietary/vendor/etc/tfa98xx/btm.speaker:$(TARGET_COPY_OUT_VENDOR)/etc/tfa98xx/btm.speaker \
    vendor/sony/castor_windy/proprietary/vendor/etc/tfa98xx/coldboot.patch:$(TARGET_COPY_OUT_VENDOR)/etc/tfa98xx/coldboot.patch \
    vendor/sony/castor_windy/proprietary/vendor/etc/tfa98xx/top.speaker:$(TARGET_COPY_OUT_VENDOR)/etc/tfa98xx/top.speaker \
    vendor/sony/castor_windy/proprietary/usr/idc/clearpad.idc:$(TARGET_COPY_OUT_SYSTEM)/usr/idc/clearpad.idc \
    vendor/sony/castor_windy/proprietary/vendor/camera/LGI02BN1/cam_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI02BN1/cam_ctrl.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/LGI02BN1/cap_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI02BN1/cap_ctrl.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/LGI02BN1/chokoball.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI02BN1/chokoball.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/LGI02BN1/color_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI02BN1/color_ctrl.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/LGI02BN1/dataflow.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI02BN1/dataflow.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/LGI02BN1/debug_mgr.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI02BN1/debug_mgr.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/LGI02BN1/exposure_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI02BN1/exposure_ctrl.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/LGI02BN1/face_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI02BN1/face_detector.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/LGI02BN1/flicker_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI02BN1/flicker_detector.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/LGI02BN1/focus_stats_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI02BN1/focus_stats_conv.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/LGI02BN1/hal_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI02BN1/hal_ctrl.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/LGI02BN1/hal_ctrl_platform.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI02BN1/hal_ctrl_platform.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/LGI02BN1/hdr_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI02BN1/hdr_comp.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/LGI02BN1/idt_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI02BN1/idt_ctrl.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/LGI02BN1/image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI02BN1/image_conv.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/LGI02BN1/imgproc.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI02BN1/imgproc.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/LGI02BN1/jpeg_enc.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI02BN1/jpeg_enc.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/LGI02BN1/lens_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI02BN1/lens_ctrl.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/LGI02BN1/module.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI02BN1/module.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/LGI02BN1/motion_estimation.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI02BN1/motion_estimation.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/LGI02BN1/multiframe_nr.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI02BN1/multiframe_nr.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/LGI02BN1/object_tracker.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI02BN1/object_tracker.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/LGI02BN1/scene_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI02BN1/scene_detector.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/LGI02BN1/snapshot_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI02BN1/snapshot_ctrl.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/LGI02BN1/streaming_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI02BN1/streaming_ctrl.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/LGI02BN1_IMX132.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI02BN1_IMX132.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SEM02BN1/cam_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM02BN1/cam_ctrl.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SEM02BN1/cap_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM02BN1/cap_ctrl.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SEM02BN1/chokoball.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM02BN1/chokoball.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SEM02BN1/color_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM02BN1/color_ctrl.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SEM02BN1/dataflow.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM02BN1/dataflow.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SEM02BN1/debug_mgr.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM02BN1/debug_mgr.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SEM02BN1/exposure_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM02BN1/exposure_ctrl.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SEM02BN1/face_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM02BN1/face_detector.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SEM02BN1/flicker_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM02BN1/flicker_detector.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SEM02BN1/focus_stats_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM02BN1/focus_stats_conv.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SEM02BN1/hal_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM02BN1/hal_ctrl.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SEM02BN1/hal_ctrl_platform.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM02BN1/hal_ctrl_platform.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SEM02BN1/hdr_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM02BN1/hdr_comp.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SEM02BN1/idt_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM02BN1/idt_ctrl.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SEM02BN1/image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM02BN1/image_conv.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SEM02BN1/imgproc.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM02BN1/imgproc.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SEM02BN1/jpeg_enc.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM02BN1/jpeg_enc.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SEM02BN1/lens_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM02BN1/lens_ctrl.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SEM02BN1/module.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM02BN1/module.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SEM02BN1/motion_estimation.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM02BN1/motion_estimation.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SEM02BN1/multiframe_nr.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM02BN1/multiframe_nr.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SEM02BN1/object_tracker.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM02BN1/object_tracker.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SEM02BN1/scene_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM02BN1/scene_detector.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SEM02BN1/snapshot_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM02BN1/snapshot_ctrl.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SEM02BN1/streaming_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM02BN1/streaming_ctrl.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SEM02BN1_IMX132.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM02BN1_IMX132.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SOI08BS2/cam_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/cam_ctrl.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SOI08BS2/cap_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/cap_ctrl.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SOI08BS2/chokoball.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/chokoball.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SOI08BS2/color_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/color_ctrl.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SOI08BS2/dataflow.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/dataflow.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SOI08BS2/debug_mgr.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/debug_mgr.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SOI08BS2/exposure_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/exposure_ctrl.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SOI08BS2/face_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/face_detector.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SOI08BS2/flicker_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/flicker_detector.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SOI08BS2/focus_stats_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/focus_stats_conv.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SOI08BS2/hal_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/hal_ctrl.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SOI08BS2/hal_ctrl_platform.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/hal_ctrl_platform.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SOI08BS2/hdr_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/hdr_comp.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SOI08BS2/idt_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/idt_ctrl.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SOI08BS2/image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/image_conv.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SOI08BS2/imgproc.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/imgproc.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SOI08BS2/jpeg_enc.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/jpeg_enc.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SOI08BS2/lens_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/lens_ctrl.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SOI08BS2/module.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/module.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SOI08BS2/motion_estimation.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/motion_estimation.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SOI08BS2/multiframe_nr.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/multiframe_nr.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SOI08BS2/object_tracker.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/object_tracker.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SOI08BS2/scene_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/scene_detector.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SOI08BS2/snapshot_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/snapshot_ctrl.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SOI08BS2/streaming_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/streaming_ctrl.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SOI08BS2_BU64291GWZ.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2_BU64291GWZ.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/SOI08BS2_IMX134.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2_IMX134.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/product.dat:$(TARGET_COPY_OUT_VENDOR)/camera/product.dat \
    vendor/sony/castor_windy/proprietary/vendor/camera/product_CACAO.dat:$(TARGET_COPY_OUT_VENDOR)/camera/product_CACAO.dat
