# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/nypon/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/sony/nypon/proprietary/vendor/camera/product.dat:system/vendor/camera/product.dat \
    vendor/sony/nypon/proprietary/vendor/camera/APT00YP1.dat:system/vendor/camera/APT00YP1.dat \
    vendor/sony/nypon/proprietary/vendor/camera/KMO08BN0_BU6456.dat:system/vendor/camera/KMO08BN0_BU6456.dat \
    vendor/sony/nypon/proprietary/vendor/camera/SOI08BN1.dat:system/vendor/camera/SOI08BN1.dat \
    vendor/sony/nypon/proprietary/vendor/camera/SOI08BN1_LC0810.dat:system/vendor/camera/SOI08BN1_LC0810.dat \
    vendor/sony/nypon/proprietary/vendor/camera/KMO08BN0.dat:system/vendor/camera/KMO08BN0.dat \
    vendor/sony/nypon/proprietary/vendor/camera/flash.dat:system/vendor/camera/flash.dat \
    vendor/sony/nypon/proprietary/xbin/ste-cg29xx_ctrl:system/xbin/ste-cg29xx_ctrl \
    vendor/sony/nypon/proprietary/xbin/watchdog-kicker:system/xbin/watchdog-kicker \
    vendor/sony/nypon/proprietary/etc/AT/model_id.cfg:system/etc/AT/model_id.cfg \
    vendor/sony/nypon/proprietary/etc/AT/manuf_id.cfg:system/etc/AT/manuf_id.cfg \
    vendor/sony/nypon/proprietary/etc/AT/system_id.cfg:system/etc/AT/system_id.cfg \
    vendor/sony/nypon/proprietary/usr/share/camera/tuning/ChrLin-020111.nmx:system/usr/share/camera/tuning/ChrLin-020111.nmx \
    vendor/sony/nypon/proprietary/usr/share/camera/tuning/TunCommon-030111.xml:system/usr/share/camera/tuning/TunCommon-030111.xml \
    vendor/sony/nypon/proprietary/usr/share/camera/tuning/ChrOth-030111.bin:system/usr/share/camera/tuning/ChrOth-030111.bin \
    vendor/sony/nypon/proprietary/usr/share/camera/tuning/TunVidRec-020111.xml:system/usr/share/camera/tuning/TunVidRec-020111.xml \
    vendor/sony/nypon/proprietary/usr/share/camera/tuning/TunStiCap-020111.xml:system/usr/share/camera/tuning/TunStiCap-020111.xml \
    vendor/sony/nypon/proprietary/usr/share/camera/tuning/TunStiPre-020111.xml:system/usr/share/camera/tuning/TunStiPre-020111.xml \
    vendor/sony/nypon/proprietary/usr/share/camera/tuning/TunVidRec-030111.xml:system/usr/share/camera/tuning/TunVidRec-030111.xml \
    vendor/sony/nypon/proprietary/usr/share/camera/tuning/TunVidPre-030111.xml:system/usr/share/camera/tuning/TunVidPre-030111.xml \
    vendor/sony/nypon/proprietary/usr/share/camera/tuning/TunStiCap-030111.xml:system/usr/share/camera/tuning/TunStiCap-030111.xml \
    vendor/sony/nypon/proprietary/usr/share/camera/tuning/ChrLsc-020111.nmx:system/usr/share/camera/tuning/ChrLsc-020111.nmx \
    vendor/sony/nypon/proprietary/usr/share/camera/tuning/ChrOth-020111.bin:system/usr/share/camera/tuning/ChrOth-020111.bin \
    vendor/sony/nypon/proprietary/usr/share/camera/tuning/TunCommon-020111.xml:system/usr/share/camera/tuning/TunCommon-020111.xml \
    vendor/sony/nypon/proprietary/usr/share/camera/tuning/ChrLsc-030111.nmx:system/usr/share/camera/tuning/ChrLsc-030111.nmx \
    vendor/sony/nypon/proprietary/usr/share/camera/tuning/TunVidPre-020111.xml:system/usr/share/camera/tuning/TunVidPre-020111.xml \
    vendor/sony/nypon/proprietary/usr/share/camera/tuning/TunStiPre-030111.xml:system/usr/share/camera/tuning/TunStiPre-030111.xml \
    vendor/sony/nypon/proprietary/usr/share/camera/tuning/ChrLin-030111.nmx:system/usr/share/camera/tuning/ChrLin-030111.nmx \
    vendor/sony/nypon/proprietary/usr/share/camera/config_file/omnivision_ov5640_pri_30fps.dat:system/usr/share/camera/config_file/omnivision_ov5640_pri_30fps.dat \
    vendor/sony/nypon/proprietary/usr/share/camera/config_file/sony_isx006.dat:system/usr/share/camera/config_file/sony_isx006.dat \
    vendor/sony/nypon/proprietary/usr/share/camera/config_file/aptina_mt9v113.dat:system/usr/share/camera/config_file/aptina_mt9v113.dat \
    vendor/sony/nypon/proprietary/usr/share/camera/config_file/omnivision_ov5640_sec.dat:system/usr/share/camera/config_file/omnivision_ov5640_sec.dat \
    vendor/sony/nypon/proprietary/usr/share/camera/config_file/omnivision_ov5640_pri.dat:system/usr/share/camera/config_file/omnivision_ov5640_pri.dat \
    vendor/sony/nypon/proprietary/usr/share/camera/config_file/aptina_mt9v115.dat:system/usr/share/camera/config_file/aptina_mt9v115.dat \
    vendor/sony/nypon/proprietary/lib/libcameraservice.so:system/lib/libcameraservice.so \
    vendor/sony/nypon/proprietary/lib/libcamera_clientsemc.so:system/lib/libcamera_clientsemc.so \
    vendor/sony/nypon/proprietary/lib/libcald_server.so:system/lib/libcald_server.so \
    vendor/sony/nypon/proprietary/lib/libcameralight.so:system/lib/libcameralight.so \
    vendor/sony/nypon/proprietary/lib/libcameraextensionservice.so:system/lib/libcameraextensionservice.so \
    vendor/sony/nypon/proprietary/lib/libcflashdriver.so:system/lib/libcflashdriver.so \
    vendor/sony/nypon/proprietary/lib/libcald_imageutil.so:system/lib/libcald_imageutil.so \
    vendor/sony/nypon/proprietary/lib/libcameraextensionclient.so:system/lib/libcameraextensionclient.so \
    vendor/sony/nypon/proprietary/lib/libcald_client.so:system/lib/libcald_client.so \
    vendor/sony/nypon/proprietary/lib/libsys-utils.so:system/lib/libsys-utils.so \
    vendor/sony/nypon/proprietary/lib/hw/nfc.montblanc.so:system/lib/hw/nfc.montblanc.so \
    vendor/sony/nypon/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
    vendor/sony/nypon/proprietary/lib/hw/camera.montblanc.so:system/lib/hw/camera.montblanc.so \
    vendor/sony/nypon/proprietary/lib/libcald_util.so:system/lib/libcald_util.so \
    vendor/sony/nypon/proprietary/lib/libface.so:system/lib/libface.so \
    vendor/sony/nypon/proprietary/lib/libals.so:system/lib/libals.so \
    vendor/sony/nypon/proprietary/lib/libcald_hal.so:system/lib/libcald_hal.so \
    vendor/sony/nypon/proprietary/lib/libcameraextensionjni.so:system/lib/libcameraextensionjni.so \
    vendor/sony/nypon/proprietary/lib/libcamera_client.so:system/lib/libcamera_client.so \
    vendor/sony/nypon/proprietary/lib/libcald_pal.so:system/lib/libcald_pal.so
