# Copyright (C) 2011-2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/scorpion_windy/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/sony/scorpion_windy/proprietary/etc/acdbdata/Handset_cal.acdb:system/etc/acdbdata/Handset_cal.acdb \
    vendor/sony/scorpion_windy/proprietary/etc/acdbdata/Speaker_cal.acdb:system/etc/acdbdata/Speaker_cal.acdb \
    vendor/sony/scorpion_windy/proprietary/etc/firmware/adsp.b00:system/etc/firmware/adsp.b00 \
    vendor/sony/scorpion_windy/proprietary/etc/firmware/adsp.b01:system/etc/firmware/adsp.b01 \
    vendor/sony/scorpion_windy/proprietary/etc/firmware/adsp.b02:system/etc/firmware/adsp.b02 \
    vendor/sony/scorpion_windy/proprietary/etc/firmware/adsp.b03:system/etc/firmware/adsp.b03 \
    vendor/sony/scorpion_windy/proprietary/etc/firmware/adsp.b04:system/etc/firmware/adsp.b04 \
    vendor/sony/scorpion_windy/proprietary/etc/firmware/adsp.b05:system/etc/firmware/adsp.b05 \
    vendor/sony/scorpion_windy/proprietary/etc/firmware/adsp.b06:system/etc/firmware/adsp.b06 \
    vendor/sony/scorpion_windy/proprietary/etc/firmware/adsp.b07:system/etc/firmware/adsp.b07 \
    vendor/sony/scorpion_windy/proprietary/etc/firmware/adsp.b08:system/etc/firmware/adsp.b08 \
    vendor/sony/scorpion_windy/proprietary/etc/firmware/adsp.b09:system/etc/firmware/adsp.b09 \
    vendor/sony/scorpion_windy/proprietary/etc/firmware/adsp.b10:system/etc/firmware/adsp.b10 \
    vendor/sony/scorpion_windy/proprietary/etc/firmware/adsp.b11:system/etc/firmware/adsp.b11 \
    vendor/sony/scorpion_windy/proprietary/etc/firmware/adsp.b12:system/etc/firmware/adsp.b12 \
    vendor/sony/scorpion_windy/proprietary/etc/firmware/adsp.mdt:system/etc/firmware/adsp.mdt \
    vendor/sony/scorpion_windy/proprietary/etc/firmware/mba.b00:system/etc/firmware/mba.b00 \
    vendor/sony/scorpion_windy/proprietary/etc/firmware/mba.mdt:system/etc/firmware/mba.mdt \
    vendor/sony/scorpion_windy/proprietary/etc/firmware/touch_module_id_0x97.img:system/etc/firmware/touch_module_id_0x97.img \
    vendor/sony/scorpion_windy/proprietary/etc/firmware/touch_module_id_0x98.img:system/etc/firmware/touch_module_id_0x98.img \
    vendor/sony/scorpion_windy/proprietary/etc/firmware/touch_module_id_0x99.img:system/etc/firmware/touch_module_id_0x99.img \
    vendor/sony/scorpion_windy/proprietary/etc/firmware/touch_module_id_0x9a.img:system/etc/firmware/touch_module_id_0x9a.img \
    vendor/sony/scorpion_windy/proprietary/etc/firmware/touch_module_id_0xa4.img:system/etc/firmware/touch_module_id_0xa4.img \
    vendor/sony/scorpion_windy/proprietary/etc/firmware/touch_module_id_0xa5.img:system/etc/firmware/touch_module_id_0xa5.img \
    vendor/sony/scorpion_windy/proprietary/etc/firmware/touch_module_id_0xa6.img:system/etc/firmware/touch_module_id_0xa6.img \
    vendor/sony/scorpion_windy/proprietary/etc/firmware/touch_module_id_0xa7.img:system/etc/firmware/touch_module_id_0xa7.img \
    vendor/sony/scorpion_windy/proprietary/etc/firmware/touch_module_id_0xa8.img:system/etc/firmware/touch_module_id_0xa8.img \
    vendor/sony/scorpion_windy/proprietary/etc/firmware/touch_module_id_0xa9.img:system/etc/firmware/touch_module_id_0xa9.img \
    vendor/sony/scorpion_windy/proprietary/etc/firmware/tzhdcp.b00:system/etc/firmware/tzhdcp.b00 \
    vendor/sony/scorpion_windy/proprietary/etc/firmware/tzhdcp.b01:system/etc/firmware/tzhdcp.b01 \
    vendor/sony/scorpion_windy/proprietary/etc/firmware/tzhdcp.b02:system/etc/firmware/tzhdcp.b02 \
    vendor/sony/scorpion_windy/proprietary/etc/firmware/tzhdcp.b03:system/etc/firmware/tzhdcp.b03 \
    vendor/sony/scorpion_windy/proprietary/etc/firmware/tzhdcp.mdt:system/etc/firmware/tzhdcp.mdt \
    vendor/sony/scorpion_windy/proprietary/etc/tfa98xx/FMSpeaker_btm.eq:system/etc/tfa98xx/FMSpeaker_btm.eq \
    vendor/sony/scorpion_windy/proprietary/etc/tfa98xx/FMSpeaker_btm.preset:system/etc/tfa98xx/FMSpeaker_btm.preset \
    vendor/sony/scorpion_windy/proprietary/etc/tfa98xx/FMSpeaker_top.eq:system/etc/tfa98xx/FMSpeaker_top.eq \
    vendor/sony/scorpion_windy/proprietary/etc/tfa98xx/FMSpeaker_top.preset:system/etc/tfa98xx/FMSpeaker_top.preset \
    vendor/sony/scorpion_windy/proprietary/etc/tfa98xx/HiFiSpeakerRing_btm.eq:system/etc/tfa98xx/HiFiSpeakerRing_btm.eq \
    vendor/sony/scorpion_windy/proprietary/etc/tfa98xx/HiFiSpeakerRing_btm.preset:system/etc/tfa98xx/HiFiSpeakerRing_btm.preset \
    vendor/sony/scorpion_windy/proprietary/etc/tfa98xx/HiFiSpeakerRing_top.eq:system/etc/tfa98xx/HiFiSpeakerRing_top.eq \
    vendor/sony/scorpion_windy/proprietary/etc/tfa98xx/HiFiSpeakerRing_top.preset:system/etc/tfa98xx/HiFiSpeakerRing_top.preset \
    vendor/sony/scorpion_windy/proprietary/etc/tfa98xx/HiFiSpeakerSforce_btm.eq:system/etc/tfa98xx/HiFiSpeakerSforce_btm.eq \
    vendor/sony/scorpion_windy/proprietary/etc/tfa98xx/HiFiSpeakerSforce_btm.preset:system/etc/tfa98xx/HiFiSpeakerSforce_btm.preset \
    vendor/sony/scorpion_windy/proprietary/etc/tfa98xx/HiFiSpeakerSforce_top.eq:system/etc/tfa98xx/HiFiSpeakerSforce_top.eq \
    vendor/sony/scorpion_windy/proprietary/etc/tfa98xx/HiFiSpeakerSforce_top.preset:system/etc/tfa98xx/HiFiSpeakerSforce_top.preset \
    vendor/sony/scorpion_windy/proprietary/etc/tfa98xx/HiFiSpeaker_btm.eq:system/etc/tfa98xx/HiFiSpeaker_btm.eq \
    vendor/sony/scorpion_windy/proprietary/etc/tfa98xx/HiFiSpeaker_btm.preset:system/etc/tfa98xx/HiFiSpeaker_btm.preset \
    vendor/sony/scorpion_windy/proprietary/etc/tfa98xx/HiFiSpeaker_top.eq:system/etc/tfa98xx/HiFiSpeaker_top.eq \
    vendor/sony/scorpion_windy/proprietary/etc/tfa98xx/HiFiSpeaker_top.preset:system/etc/tfa98xx/HiFiSpeaker_top.preset \
    vendor/sony/scorpion_windy/proprietary/etc/tfa98xx/TFA9890.patch:system/etc/tfa98xx/TFA9890.patch \
    vendor/sony/scorpion_windy/proprietary/etc/tfa98xx/TFA9890_Receiver.config:system/etc/tfa98xx/TFA9890_Receiver.config \
    vendor/sony/scorpion_windy/proprietary/etc/tfa98xx/TFA9890_btm.config:system/etc/tfa98xx/TFA9890_btm.config \
    vendor/sony/scorpion_windy/proprietary/etc/tfa98xx/TFA9890_top.config:system/etc/tfa98xx/TFA9890_top.config \
    vendor/sony/scorpion_windy/proprietary/etc/tfa98xx/VoiceCallEarpice_top.eq:system/etc/tfa98xx/VoiceCallEarpice_top.eq \
    vendor/sony/scorpion_windy/proprietary/etc/tfa98xx/VoiceCallEarpice_top.preset:system/etc/tfa98xx/VoiceCallEarpice_top.preset \
    vendor/sony/scorpion_windy/proprietary/etc/tfa98xx/VoiceCallSpeaker_btm.eq:system/etc/tfa98xx/VoiceCallSpeaker_btm.eq \
    vendor/sony/scorpion_windy/proprietary/etc/tfa98xx/VoiceCallSpeaker_btm.preset:system/etc/tfa98xx/VoiceCallSpeaker_btm.preset \
    vendor/sony/scorpion_windy/proprietary/etc/tfa98xx/VoiceCallSpeaker_top.eq:system/etc/tfa98xx/VoiceCallSpeaker_top.eq \
    vendor/sony/scorpion_windy/proprietary/etc/tfa98xx/VoiceCallSpeaker_top.preset:system/etc/tfa98xx/VoiceCallSpeaker_top.preset \
    vendor/sony/scorpion_windy/proprietary/etc/tfa98xx/btm.speaker:system/etc/tfa98xx/btm.speaker \
    vendor/sony/scorpion_windy/proprietary/etc/tfa98xx/coldboot.patch:system/etc/tfa98xx/coldboot.patch \
    vendor/sony/scorpion_windy/proprietary/etc/tfa98xx/top.speaker:system/etc/tfa98xx/top.speaker \
    vendor/sony/scorpion_windy/proprietary/usr/idc/clearpad.idc:system/usr/idc/clearpad.idc \
    vendor/sony/scorpion_windy/proprietary/vendor/firmware/fw_bcmdhd.bin:system/vendor/firmware/fw_bcmdhd.bin \
    vendor/sony/scorpion_windy/proprietary/vendor/firmware/fw_bcmdhd_apsta.bin:system/vendor/firmware/fw_bcmdhd_apsta.bin
