# Copyright (C) 2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/suzu/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/sony/suzu/proprietary/etc/acdbdata/Sony/Sony_loire_Bluetooth_cal.acdb:system/etc/acdbdata/Sony/Sony_loire_Bluetooth_cal.acdb \
    vendor/sony/suzu/proprietary/etc/acdbdata/Sony/Sony_loire_General_cal.acdb:system/etc/acdbdata/Sony/Sony_loire_General_cal.acdb \
    vendor/sony/suzu/proprietary/etc/acdbdata/Sony/Sony_loire_Global_cal.acdb:system/etc/acdbdata/Sony/Sony_loire_Global_cal.acdb \
    vendor/sony/suzu/proprietary/etc/acdbdata/Sony/Sony_loire_Handset_cal.acdb:system/etc/acdbdata/Sony/Sony_loire_Handset_cal.acdb \
    vendor/sony/suzu/proprietary/etc/acdbdata/Sony/Sony_loire_Hdmi_cal.acdb:system/etc/acdbdata/Sony/Sony_loire_Hdmi_cal.acdb \
    vendor/sony/suzu/proprietary/etc/acdbdata/Sony/Sony_loire_Headset_cal.acdb:system/etc/acdbdata/Sony/Sony_loire_Headset_cal.acdb \
    vendor/sony/suzu/proprietary/etc/acdbdata/Sony/Sony_loire_Speaker_cal.acdb:system/etc/acdbdata/Sony/Sony_loire_Speaker_cal.acdb \
    vendor/sony/suzu/proprietary/etc/firmware/touch_module_id_0x90.img:system/etc/firmware/touch_module_id_0x90.img \
    vendor/sony/suzu/proprietary/etc/firmware/touch_module_id_0x91.img:system/etc/firmware/touch_module_id_0x91.img \
    vendor/sony/suzu/proprietary/etc/firmware/touch_module_id_0x92.img:system/etc/firmware/touch_module_id_0x92.img \
    vendor/sony/suzu/proprietary/etc/firmware/touch_module_id_0x93.img:system/etc/firmware/touch_module_id_0x93.img \
    vendor/sony/suzu/proprietary/etc/firmware/touch_module_id_0x94.img:system/etc/firmware/touch_module_id_0x94.img \
    vendor/sony/suzu/proprietary/vendor/bin/qns:$(TARGET_COPY_OUT_VENDOR)/bin/qns \
    vendor/sony/suzu/proprietary/vendor/camera/SEM13BS0/color_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM13BS0/color_ctrl.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SEM13BS0/dataflow.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM13BS0/dataflow.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SEM13BS0/exposure_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM13BS0/exposure_ctrl.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SEM13BS0/exposure_ctrl_diagram.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM13BS0/exposure_ctrl_diagram.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SEM13BS0/exposure_ctrl_gamma.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM13BS0/exposure_ctrl_gamma.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SEM13BS0/face_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM13BS0/face_detector.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SEM13BS0/flicker_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM13BS0/flicker_detector.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SEM13BS0/focus_stats_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM13BS0/focus_stats_conv.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SEM13BS0/food_comp_yummy.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM13BS0/food_comp_yummy.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SEM13BS0/food_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM13BS0/food_detector.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SEM13BS0/hal_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM13BS0/hal_ctrl.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SEM13BS0/hal_ctrl_platform.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM13BS0/hal_ctrl_platform.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SEM13BS0/hal_ctrl_platform_abf.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM13BS0/hal_ctrl_platform_abf.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SEM13BS0/hal_ctrl_platform_asf_lin.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM13BS0/hal_ctrl_platform_asf_lin.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SEM13BS0/hal_ctrl_platform_asf_stp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM13BS0/hal_ctrl_platform_asf_stp.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SEM13BS0/hal_ctrl_platform_ltm.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM13BS0/hal_ctrl_platform_ltm.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SEM13BS0/hdr_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM13BS0/hdr_comp.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SEM13BS0/idt_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM13BS0/idt_ctrl.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SEM13BS0/image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM13BS0/image_conv.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SEM13BS0/image_conv_canele.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM13BS0/image_conv_canele.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SEM13BS0/image_conv_cheesescone.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM13BS0/image_conv_cheesescone.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SEM13BS0/image_conv_dars.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM13BS0/image_conv_dars.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SEM13BS0/image_conv_marble.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM13BS0/image_conv_marble.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SEM13BS0/image_conv_raisin.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM13BS0/image_conv_raisin.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SEM13BS0/image_conv_spica.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM13BS0/image_conv_spica.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SEM13BS0/lens_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM13BS0/lens_ctrl.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SEM13BS0/motion_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM13BS0/motion_detector.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SEM13BS0/motion_detector_sumomo.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM13BS0/motion_detector_sumomo.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SEM13BS0/motion_estimation.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM13BS0/motion_estimation.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SEM13BS0/multiframe_nr.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM13BS0/multiframe_nr.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SEM13BS0/multiframe_nr_melonpan.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM13BS0/multiframe_nr_melonpan.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SEM13BS0/multiframe_nr_mugichoco.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM13BS0/multiframe_nr_mugichoco.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SEM13BS0/multiframe_nr_toppo.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM13BS0/multiframe_nr_toppo.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SEM13BS0/object_tracker.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM13BS0/object_tracker.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SEM13BS0/prc_image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM13BS0/prc_image_conv.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SEM13BS0/scene_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM13BS0/scene_detector.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SEM13BS0_LC898217XC.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM13BS0_LC898217XC.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SOI13BS0/color_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0/color_ctrl.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SOI13BS0/dataflow.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0/dataflow.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SOI13BS0/exposure_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0/exposure_ctrl.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SOI13BS0/exposure_ctrl_diagram.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0/exposure_ctrl_diagram.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SOI13BS0/exposure_ctrl_gamma.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0/exposure_ctrl_gamma.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SOI13BS0/face_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0/face_detector.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SOI13BS0/flicker_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0/flicker_detector.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SOI13BS0/focus_stats_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0/focus_stats_conv.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SOI13BS0/food_comp_yummy.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0/food_comp_yummy.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SOI13BS0/food_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0/food_detector.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SOI13BS0/hal_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0/hal_ctrl.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SOI13BS0/hal_ctrl_platform.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0/hal_ctrl_platform.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SOI13BS0/hal_ctrl_platform_abf.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0/hal_ctrl_platform_abf.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SOI13BS0/hal_ctrl_platform_asf_lin.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0/hal_ctrl_platform_asf_lin.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SOI13BS0/hal_ctrl_platform_asf_stp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0/hal_ctrl_platform_asf_stp.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SOI13BS0/hal_ctrl_platform_ltm.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0/hal_ctrl_platform_ltm.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SOI13BS0/hdr_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0/hdr_comp.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SOI13BS0/idt_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0/idt_ctrl.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SOI13BS0/image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0/image_conv.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SOI13BS0/image_conv_canele.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0/image_conv_canele.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SOI13BS0/image_conv_cheesescone.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0/image_conv_cheesescone.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SOI13BS0/image_conv_dars.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0/image_conv_dars.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SOI13BS0/image_conv_marble.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0/image_conv_marble.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SOI13BS0/image_conv_raisin.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0/image_conv_raisin.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SOI13BS0/image_conv_spica.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0/image_conv_spica.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SOI13BS0/lens_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0/lens_ctrl.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SOI13BS0/motion_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0/motion_detector.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SOI13BS0/motion_detector_sumomo.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0/motion_detector_sumomo.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SOI13BS0/motion_estimation.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0/motion_estimation.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SOI13BS0/multiframe_nr.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0/multiframe_nr.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SOI13BS0/multiframe_nr_melonpan.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0/multiframe_nr_melonpan.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SOI13BS0/multiframe_nr_mugichoco.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0/multiframe_nr_mugichoco.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SOI13BS0/multiframe_nr_toppo.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0/multiframe_nr_toppo.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SOI13BS0/object_tracker.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0/object_tracker.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SOI13BS0/prc_image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0/prc_image_conv.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SOI13BS0/scene_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0/scene_detector.dat \
    vendor/sony/suzu/proprietary/vendor/camera/SOI13BS0_LC898217XC.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0_LC898217XC.dat \
    vendor/sony/suzu/proprietary/vendor/camera/default.dat:$(TARGET_COPY_OUT_VENDOR)/camera/default.dat \
    vendor/sony/suzu/proprietary/vendor/camera/flash.dat:$(TARGET_COPY_OUT_VENDOR)/camera/flash.dat \
    vendor/sony/suzu/proprietary/vendor/camera/snapshot.dat:$(TARGET_COPY_OUT_VENDOR)/camera/snapshot.dat \
    vendor/sony/suzu/proprietary/vendor/camera/streaming.dat:$(TARGET_COPY_OUT_VENDOR)/camera/streaming.dat \
    vendor/sony/suzu/proprietary/vendor/camera/supported.dat:$(TARGET_COPY_OUT_VENDOR)/camera/supported.dat \
    vendor/sony/suzu/proprietary/vendor/camera/version.dat:$(TARGET_COPY_OUT_VENDOR)/camera/version.dat \
    vendor/sony/suzu/proprietary/vendor/lib/libcammw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcammw.so
