# Copyright (C) 2011-2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/togari_gpe/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/sony/togari_gpe/proprietary/etc/firmware/adsp.b00:system/etc/firmware/adsp.b00 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/adsp.b01:system/etc/firmware/adsp.b01 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/adsp.b02:system/etc/firmware/adsp.b02 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/adsp.b03:system/etc/firmware/adsp.b03 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/adsp.b04:system/etc/firmware/adsp.b04 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/adsp.b05:system/etc/firmware/adsp.b05 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/adsp.b06:system/etc/firmware/adsp.b06 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/adsp.b07:system/etc/firmware/adsp.b07 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/adsp.b08:system/etc/firmware/adsp.b08 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/adsp.b09:system/etc/firmware/adsp.b09 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/adsp.b10:system/etc/firmware/adsp.b10 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/adsp.b11:system/etc/firmware/adsp.b11 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/adsp.mdt:system/etc/firmware/adsp.mdt \
    vendor/sony/togari_gpe/proprietary/etc/firmware/cmnlib.b00:system/etc/firmware/cmnlib.b00 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/cmnlib.b01:system/etc/firmware/cmnlib.b01 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/cmnlib.b02:system/etc/firmware/cmnlib.b02 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/cmnlib.b03:system/etc/firmware/cmnlib.b03 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/cmnlib.mdt:system/etc/firmware/cmnlib.mdt \
    vendor/sony/togari_gpe/proprietary/etc/firmware/mba.b00:system/etc/firmware/mba.b00 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/mba.mdt:system/etc/firmware/mba.mdt \
    vendor/sony/togari_gpe/proprietary/etc/firmware/modem.b00:system/etc/firmware/modem.b00 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/modem.b01:system/etc/firmware/modem.b01 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/modem.b02:system/etc/firmware/modem.b02 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/modem.b03:system/etc/firmware/modem.b03 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/modem.b04:system/etc/firmware/modem.b04 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/modem.b05:system/etc/firmware/modem.b05 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/modem.b08:system/etc/firmware/modem.b08 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/modem.b11:system/etc/firmware/modem.b11 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/modem.b13:system/etc/firmware/modem.b13 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/modem.b14:system/etc/firmware/modem.b14 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/modem.b15:system/etc/firmware/modem.b15 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/modem.b16:system/etc/firmware/modem.b16 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/modem.b17:system/etc/firmware/modem.b17 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/modem.b18:system/etc/firmware/modem.b18 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/modem.b19:system/etc/firmware/modem.b19 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/modem.b20:system/etc/firmware/modem.b20 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/modem.b21:system/etc/firmware/modem.b21 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/modem.b22:system/etc/firmware/modem.b22 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/modem.b25:system/etc/firmware/modem.b25 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/modem.b26:system/etc/firmware/modem.b26 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/modem.mdt:system/etc/firmware/modem.mdt \
    vendor/sony/togari_gpe/proprietary/etc/firmware/touch_chip_id_0x75_config_id_0x0010.bin:system/etc/firmware/touch_chip_id_0x75_config_id_0x0010.bin \
    vendor/sony/togari_gpe/proprietary/etc/firmware/touch_chip_id_0x75_config_id_0x0012.bin:system/etc/firmware/touch_chip_id_0x75_config_id_0x0012.bin \
    vendor/sony/togari_gpe/proprietary/etc/firmware/touch_chip_id_0x75_config_id_0x0013.bin:system/etc/firmware/touch_chip_id_0x75_config_id_0x0013.bin \
    vendor/sony/togari_gpe/proprietary/etc/firmware/tzhdcp.b00:system/etc/firmware/tzhdcp.b00 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/tzhdcp.b01:system/etc/firmware/tzhdcp.b01 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/tzhdcp.b02:system/etc/firmware/tzhdcp.b02 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/tzhdcp.b03:system/etc/firmware/tzhdcp.b03 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/tzlibasb.b00:system/etc/firmware/tzlibasb.b00 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/tzlibasb.b01:system/etc/firmware/tzlibasb.b01 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/tzlibasb.b02:system/etc/firmware/tzlibasb.b02 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/tzlibasb.b03:system/etc/firmware/tzlibasb.b03 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/tzlibasb.mdt:system/etc/firmware/tzlibasb.mdt \
    vendor/sony/togari_gpe/proprietary/etc/firmware/tzsuntory.b00:system/etc/firmware/tzsuntory.b00 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/tzsuntory.b01:system/etc/firmware/tzsuntory.b01 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/tzsuntory.b02:system/etc/firmware/tzsuntory.b02 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/tzsuntory.b03:system/etc/firmware/tzsuntory.b03 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/tzsuntory.mdt:system/etc/firmware/tzsuntory.mdt \
    vendor/sony/togari_gpe/proprietary/etc/firmware/tzwidevine.b00:system/etc/firmware/tzwidevine.b00 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/tzwidevine.b01:system/etc/firmware/tzwidevine.b01 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/tzwidevine.b02:system/etc/firmware/tzwidevine.b02 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/tzwidevine.b03:system/etc/firmware/tzwidevine.b03 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/widevine.b00:system/etc/firmware/widevine.b00 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/widevine.b01:system/etc/firmware/widevine.b01 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/widevine.b02:system/etc/firmware/widevine.b02 \
    vendor/sony/togari_gpe/proprietary/etc/firmware/widevine.b03:system/etc/firmware/widevine.b03
